### ISSUE TITLE
[Feature] Double stack of Cheese

### ISSUE THREAD

**Issue by Syndaryl** [GrowthcraftCE/Growthcraft-1.12#104]
Future feature: 

- [x] Allow intact cheese wheels to stack as "double-slabs" - two wheels of the same type, same waxing status, same maturation stacked on top of each other
- [ ] Fancy option: Allow mixing cheese types/maturation/waxing
- [x] Advanced option: stack sliced cheeses

Request: Double-stacked cheeses should not carve off slices of cheese when interacted with - it's confusing if you have to question "destacking" the cheese vs breaking the double stack vs cutting it up.

**Comment by Avatair** [comment]
Feature has been implemented
