### ISSUE TITLE
[Feature] Cheese Slicer

### ISSUE THREAD

**Issue by Syndaryl** [GrowthcraftCE/Growthcraft-1.12#105]
Feature request: only slice cheese wheels when clicked on with a cheese slicer object. I keep breaking chunks off my beautiful decorative cheese wheels by accident QQ

**Comment by Avatair** [comment]
Will get in handy if have cheese blocks with two stacked wheels. There will be more potential of such accidents.

**Comment by Avatair** [comment]
Has been implemented recently
