### ISSUE TITLE
[Suggestion] Bottle Rack

### ISSUE THREAD

**Issue by Deshiba** [GrowthcraftCE/Growthcraft-1.12#106]
I'd like to suggest a bottle rack. This would be a block that would be used to store bottled drinks in an aesthetic manner, so you can have them on display. For balance reason the max content should be max bottles so the contents isn't bigger then a barrel.

**Comment by Deshiba** [comment]
I was thinking 3 by 4, to make it equal to the barrel.

**Comment by Alatyami** [comment]
3x4 seems like the bottles would be really small.

**Comment by Syndaryl** [comment]
try 2x6 - More bottles could be packed in at the same size by rotating them ~20 degrees and packing them closer together. See attached quick mockup.
![image](https://user-images.githubusercontent.com/8820565/50833871-99b26f80-1320-11e9-9b78-f3670f65f363.png)

**Comment by Alatyami** [comment]
Oh nice .... that would be cool that way.

**Comment by Deshiba** [comment]
Well when looking at standing up bottles, Bibliocraft has the potion shelf:
https://www.google.com/search?client=firefox-b-ab&biw=1680&bih=936&tbm=isch&sa=1&ei=RrA0XPT0K8zPwQKEl5eAAg&q=bibliocraft+bottle+shelf&oq=bibliocraft+bottle+shelf&gs_l=img.3...135657.137914..138013...0.0..0.45.348.9......0....1..gws-wiz-img.oyXi0zoUt78#imgrc=Db2djqP0AYEzRM:

I was thinking more along the line of bottles lying down. Psychedelicraft had something similar only in a 3 by 3.

https://www.google.com/search?hl=en&biw=1680&bih=936&tbm=isch&sa=1&ei=GLE0XPW2D9LMwAKgsKvwAw&q=bottle+rack&oq=bottle+rack&gs_l=img.3.2.0i67j0l9.39456.39456..39685...0.0..0.57.57.1......0....1..gws-wiz-img.Y4Ic-P-i9Ys

**Comment by Alatyami** [comment]
We'll draft up some mock models.

**Comment by Deshiba** [comment]
@Alatyami, there's already some work done on this in the DesignDocs repo;
https://github.com/GrowthcraftCE/Growthcraft-DesignDocs/issues/2

There's even models and textures in 
https://www.dropbox.com/sh/pk00tzxq8m0gjts/AAC81ULN1esqcaNm4uVj_Agoa?dl=0

**Comment by Kisutora** [comment]
Moving to https://github.com/GrowthcraftCE/Growthcraft-1.12/issues/167
