### ISSUE TITLE
Growthcraft with IC2/ENDER IO installed bug

### ISSUE THREAD

**Issue by MadRatSRP** [GrowthcraftCE/Growthcraft-1.12#11]
[crash-2018-05-30_10.34.20-client.txt](https://github.com/GrowthcraftCE/Growthcraft-1.12/files/2059565/crash-2018-05-30_10.34.20-client.txt)
![growth](https://user-images.githubusercontent.com/29717217/40800970-74ea3480-651a-11e8-832e-3ae3c5595904.png)

**Comment by Avatair** [comment]
@MadRatSRP Please check if newer version from Discord is working.

**Comment by Alatyami** [comment]
https://github.com/GrowthcraftCE/Growthcraft-1.12/releases/tag/4.0.2.100

**Comment by MadRatSRP** [comment]
Allright, i'll try it right now.

**Comment by MadRatSRP** [comment]
Well, its seems its finally working! Thanks for you job!
