### ISSUE TITLE
Growthcraft Grapes: Grape Vines Still Breaking Without Farmland

### ISSUE THREAD

**Issue by Nakuta** [GrowthcraftCE/Growthcraft-1.12#117]
Version 4.0.4.400
-Grape vines no longer break when no longer over farmland vs. dirt.
Still bugged, jumped on the farmland under a vine and turned it to dirt, vine broke. (Oddly enough, mature thistles did not break when I did the same thing.)

**Comment by Avatair** [comment]
@Alatyami Did we introduce a change about the breaking behavior of grape vines? As far as I know they suppose to break when the farmland is destroyed. That is how it was originally programmed.

Non breaking thistles is clearly a bug.

**Comment by Deshiba** [comment]
@Avatair Yes, It's in the bugfix section of the changelog for the 4.0.4.400 release candidate.
It's there to combat  #61 .

**Comment by Nakuta** [comment]
Confirming that this is still a bug in build growthcraft-1.12.2-4.0.4.400.DEV.52b3e0d.
