### ISSUE TITLE
Growthcraft Fish trap: Loot Tables

### ISSUE THREAD

**Issue by Deshiba** [GrowthcraftCE/Growthcraft-1.12#118]
It would be nice if the Fish trap would have it's own loot table that could be edited for specific packs.

Alternatively the Fish trap could maybe use the vanilla fishing loot table. This solution would make it future proof but would reduce the chance manipulation you can do now.

**Comment by Deshiba** [comment]
Loot table reference.
https://mcforge.readthedocs.io/en/latest/items/loot_tables/

**Comment by Alatyami** [comment]
Fishtrap currently uses the vanilla fishing loot table. If you add bait it uses the fishing loot table with fortune.

**Comment by Deshiba** [comment]
:o thats cool. Time to automate that for some mending

**Comment by Alatyami** [comment]
Fishtrap also can be piped.

**Comment by Alatyami** [comment]
I'm going to leave this issue open though ... 

Gave me an idea of adding a config that would allow for extending the loot table without affecting the Fishing Loot table.

**Comment by Deshiba** [comment]
Exactly. This can be closed
