### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by SilverKytten** [GrowthcraftCE/Growthcraft-1.12#12]
This has been reported, however, not with a full report and logs.
GC v.1.12.2, Forge v.2705

[crash-2018-05-31_20.06.07-server.txt](https://github.com/GrowthcraftCE/Growthcraft-1.12/files/2060636/crash-2018-05-31_20.06.07-server.txt)
[latest.log](https://github.com/GrowthcraftCE/Growthcraft-1.12/files/2060638/latest.log)
[debug.log](https://github.com/GrowthcraftCE/Growthcraft-1.12/files/2060641/debug.log)

**Comment by Avatair** [comment]
You are using outdated version of GC. We will publish a new one at curseforge. Actually it is already available only at discord on the dev channel.

**Comment by SilverKytten** [comment]
Outdated by four days? 😂 You guys work fast.

Awesome, thank you. Just grabbed it and it's working great, so far!
