### ISSUE TITLE
Growthcraft Rice: Rice will not grow with Bonemeal without sufficient light.

### ISSUE THREAD

**Issue by Nakuta** [GrowthcraftCE/Growthcraft-1.12#136]
Test Steps:
1. Set time to 18000 (midnight).
2. Plant rice in a rice paddy.
3. Bonemeal rice crop.

Expected Result: Rice crop progresses through stages of grow per normal crop interaction with bonemeal.
Actual Result: Rice crop accepts bonemeal use but will not grow.

Conclusion: Something is preventing rice from growing without sufficient light levels, even when bonemeal is used. I put a torch near the crop at night and this fixed the issue, which is why I conclude the issue is due to light level and not the day/night cycle.

**Comment by Alatyami** [comment]
Light is set to >= 9. Going to lower to minimum and add it to the growthcraft-rice.cfg for customization.
