### ISSUE TITLE
Growthcraft Milk: Stacked food using bowls are all consumed when eating one.

### ISSUE THREAD

**Issue by Nakuta** [GrowthcraftCE/Growthcraft-1.12#137]
Test Steps:
1. Get hungry.
2. Eat from a stack of 64 Honey Yogurt.

Expected Result: One Honey Yogurt is consumed and gives you one Bowl in return.
Actual Result: The entire stack of 64 Honey Yogurt is consumed and gives you one Bowl in return.

**Comment by Alatyami** [comment]
Fixed with #158
