### ISSUE TITLE
Growthcraft Bees: Missing Honey Transfer Recipes

### ISSUE THREAD

**Issue by Nakuta** [GrowthcraftCE/Growthcraft-1.12#139]
Current, there are no recipes that allow you to turn one Honey Bucket or one Honey Jar into four Honey Bottles. Added as a bug per conversation with Avatair.

**Comment by Alatyami** [comment]
1 Bucket Honey + 4 Bottles = 4 Honey Bottles + 1 Empty Bucket

**Comment by Alatyami** [comment]
Just tested ..... you can place your honey into a fermentation barrel and then convert it to bottles.

**Comment by Deshiba** [comment]
I think you can fill bottles straight from the Honeycomb too. I do agree it's weird that there's no crafting recipe in the crafting grid though.

**Comment by Alatyami** [comment]
Going to implement this using JSON and crafting _factories.json file
