### ISSUE TITLE
Growthcraft Grapes: Visual: Sometimes grape stem is updated a wrong way

### ISSUE THREAD

**Issue by Avatair** [GrowthcraftCE/Growthcraft-1.12#141]
It is expected that small bush develops if a grape stem grows, which is sometime not the case.

![grafik](https://user-images.githubusercontent.com/21110130/51850535-39608d80-2322-11e9-8ad0-6d761502a761.png)

A plain trunk is not expected to occur, when growing naturally.

**Comment by Alatyami** [comment]
Historically this is been the way ... it looks like a trunk until it gets to the rope where it then does the vine bush.

**Comment by Alatyami** [comment]
This is no longer repeatable. I have been testing it extensively while fixing the growth direction and rate. I think we can close this one unless you can repeat it again.
