### ISSUE TITLE
Grapes not dropping from vines and apple sapling not growing....

### ISSUE THREAD

**Issue by ate0ate** [GrowthcraftCE/Growthcraft-1.12#145]
I apologize if this is simply not yet implemented, but I seem to be missing quite a few features in the latest update of this mod. I last used Growthcraft back when Gwafu was the author so I am just a little out of the loop with the Community Edition lol. I am using a rather absurdly large personal pack and seem to be unable to get grape seeds to drop from vines and cannot get the apple sapling to actually grow, though it is indeed craftable. There is also some missing configs, particularly for bamboo, so I cannot see or change the biome ID that the bamboo forest is set to nor are there any recipes for bamboo items in JEI. Am I doing something terribly wrong, or is this all just NYI? Either way, I thank you all for continuing to develop this little gem of a mod and I apologize if this is an unnecessary issue and the 1.12.2 version of the mod is just a WIP for now. Feel free to close and disregard if that is the case

**Comment by Syndaryl** [comment]
Grape seeds do not drop from vines at the moment, although you can find them in dungeon chests.
I'm not having trouble with the apple saplings, they are definitely implemented. Test without your other mods, there might be a conflict.
I'm not sure how far along the development for Bamboo is.

**Comment by Deshiba** [comment]
There's an open issue for JEI custom recipe compat:
https://github.com/GrowthcraftCE/Growthcraft-1.12/issues/54

There's some stuff that's still work in progress, but the devs are getting closer each week.

**Comment by Alatyami** [comment]
Bamboo forest was actually removed awhile back as it would tend to overgrow and take over the world. growthcraft bamboo is fully implemented with the exception of Bamboo Shoots being added to the dungeon loot table.

**Comment by ate0ate** [comment]
Okay, thanks! I'll go ahead and try and narrow down exactly what is causing any conflicts or issues then. I just wanted to be certain things were actually missing for me rather than simply not implemented. I'll go ahead and close this issue and open a more specific one if/when I find a conflict worth mentioning. Good decision to remove the bamboo forest too. I love the bamboo, but it never seemed suited to an entire biome in my opinion. Thanks again!
