### ISSUE TITLE
A few issues.

### ISSUE THREAD

**Issue by Oraiz** [GrowthcraftCE/Growthcraft-1.12#153]
Apologies in advance if this is mentioned or covered elsewhere; I think I've searched fairly extensively!

I have made a small custom pack, and have just gotten into Growthcraft to decorate my home before starting larger mods, however a few of the functions don't seem to be working:

1) I'm unable to plant hop seeds. I've tried grass, dirt, farmland, fertile soil from rustic. I have a rope hanging one block above, but have tried with ropes higher or lower (or not there at all)

2) I can't create the rice paddy (I think in old versions it was just right clicking farmland with a hoe?), so I'm not able to plant rice. I have found rice in a chest, but also I can't seem to be able to do anything with it? 

Thanks in advance for any advice, and please ask if you need to know other mods in the pack etc.

**Comment by Alatyami** [comment]
#1 - Trying placing a rope first and then the hop seeds. This makes it so that there is a rope and a hops crop in the same block space.

#2 - The old method was to use a shovel on FARMLAND, but that conflicted with another mod. In order to fix the conflict, we have the "cultivator" which acts like a hoe. using the cultivator, Dirt -> Farmland -> Rice Paddy. If the paddy with close enough to the water block, it will auto fill.

**Comment by Oraiz** [comment]
Thanks for the quick reply!

Cultivator was all I needed, sorry for being blind! :D

Still unable to plant hops on anything - I did try with a rope on the dirt too. :(

**Comment by Alatyami** [comment]
Is the farmland close to water?

**Comment by Oraiz** [comment]
Yes, I've tried a few different config with lots of water, lots of torches etc.

https://imgur.com/a/MSW8uVi

**Comment by Oraiz** [comment]
Sorry to bump, as I know this is still not fully released, so there will be issues, but I don't think my grapes are growing on to the ropes. I thought I was just being impatient, but it's been about five real-life hours without any growing.

https://imgur.com/a/q16mTp6

I have Pam's and Rustic in the pack, these are the only two I can think of that might change something to do with crops?

Thanks. :)

**Comment by Oraiz** [comment]
I feel like a complete idiot: I have been using Rustic rops, not the ones from Growthcraft. All my issues were fixed - nothing in the mod is broken, it's just my brain that's broken!! 

Sorry for my stupidity! :D

**Comment by Deshiba** [comment]
Hmm, so its a compat issue then?
Would it be possible to make the ropes interchangeable with rustic?

**Comment by Alatyami** [comment]
Should be easy enough to oredictionary it.
