### ISSUE TITLE
Still can't craft Ricotta from dried curds/bowls

### ISSUE THREAD

**Issue by mckinnsb** [GrowthcraftCE/Growthcraft-1.12#158]
Hi,

Currently using the latest dev build (500), and I can't craft ricotta cheese from the dried curds and wooden bowls.

I've noticed that in the recipe in my kitchen, the ricotta curds have no texture assigned to them.

**Comment by Alatyami** [comment]
Can you post a screenshot of how you are crafting it? And have you cleared your config files for the Growthcraft Milk cheese recipes?

**Comment by mckinnsb** [comment]
![2019-03-21_23 17 33](https://user-images.githubusercontent.com/268536/54798546-b4159d00-4c2f-11e9-9218-fbc12de12bba.png)

**Comment by mckinnsb** [comment]
How do I do the latter?

**Comment by mckinnsb** [comment]
We just started using Growthcraft 1.12 (we haven't used the previous versions), so I'm not sure the config file is at fault but I could be wrong.

**Comment by Alatyami** [comment]
Confirmed that is the recipe, I'll do testing and get back to you.

**Comment by Alatyami** [comment]
@mckinnsb can you test this again? 

The recipe works fine in testing.

![2019-08-02_09 14 55](https://user-images.githubusercontent.com/1868411/62372743-4430f080-b506-11e9-9cd1-3e7c17b60a4d.png)
