### ISSUE TITLE
Mead does not progress to "Extended" when you add Redstone

### ISSUE THREAD

**Issue by mckinnsb** [GrowthcraftCE/Growthcraft-1.12#160]
This might be the same issue as #108 , but Mead will take Redstone in the Fermentation Barrel, but will never progress to Extended.

**Comment by Alatyami** [comment]
Did you use the lastest snapshot in the GitHub releases?

**Comment by Alatyami** [comment]
Confirmed .... we missed the hyper-extended recipe.

**Comment by mckinnsb** [comment]
Apologies that this is late, but we are using the latest snapshot.
