### ISSUE TITLE
Unable to make rennet in brew kettle

### ISSUE THREAD

**Issue by vediis** [GrowthcraftCE/Growthcraft-1.12#165]
When trying to make rennet in brew kettle, the flame icon flashes repeatedly and no rennet is made. Stomach is accepted when dropped in. I'm on 1.12.2 latest, using forge 1.12.2 - 14.23.5.2768. Other mods included in screenshot.

![image](https://user-images.githubusercontent.com/12003018/56087885-3fa2d800-5e42-11e9-941a-d5b6a7239423.png)
https://media.discordapp.net/attachments/333690296334548994/566821009034838017/unknown.png?width=768&height=754

**Comment by Alatyami** [comment]
Going to test it out ... Of note, your forge is significantly behind. We build it with version 14.23.5.2768

**Comment by vedisdragon** [comment]
My bad, that was a typo. I'm running a Forge server on 1.12.2 - 14.23.5.2768.

**Comment by Alatyami** [comment]
We're unable to duplicate the issue. Tested with netherrack on fire and magma cube. 

I recommend clearing out your growthcraft configs and see if that fixes the issue.
