### ISSUE TITLE
#11 is not completely fixed...probably

### ISSUE THREAD

**Issue by MadRatSRP** [GrowthcraftCE/Growthcraft-1.12#17]
Hello, its me again. I created new world with latest ic2 and growthcraft alpha, which you sent to me. Its loaded and created perfectly, but when i try to move 1 step or another, its instantly crashes. I cant say for sure, is it a growthcraft problem or not, but i'll deffinetly test it this evening.
p.s. also, please fix that irritating "page not found" of issues on curseforge. thanks.

**Comment by Avatair** [comment]
Please sent a crash report for investigation.

**Comment by MadRatSRP** [comment]
Crashlog has no
[crash.txt](https://github.com/GrowthcraftCE/Growthcraft-1.12/files/2083555/crash.txt)
t generated, but here is information that was in minecraft window after crash:

**Comment by MadRatSRP** [comment]
I cant say for sure what caused the problem, but its not growthcraft problem) And i dont have crash now. Thanks for participating.
