### ISSUE TITLE
Mod support / compatibility  request

### ISSUE THREAD

**Issue by ziadbenaman** [GrowthcraftCE/Growthcraft-1.12#170]
If it is possible ,  please add support with Animania  and plant mega pack mods  
Thank you

**Comment by Deshiba** [comment]
Did you look trough the open issues before hand? Because for Animania we have #150 which is more specific then your request.

Can you go into more details of how a plant mega pack mod compatibility might look?

**Comment by Alatyami** [comment]
Not enough details .... if you want to include more details and reopen this request please do.
