### ISSUE TITLE
[Feature Request] Cork Tree

### ISSUE THREAD

**Issue by Deshiba** [GrowthcraftCE/Growthcraft-1.12#173]
It'd be awesome to have a cork tree in game.

This evergreen tree [would not loose it's leaves in winter](http://www.jucamuro.com/gallery/juan_carlos_munoz_rodriguez/1463162204.jpg) and could be stripped of it's cork bark by right clicking with an axe (similar to vanilla).

The tree wood itself could be used as a [distinct plank](https://thumbs.dreamstime.com/z/amur-corktree-texture-background-wood-78094645.jpg) with it's lined pattern it'd be an interesting building material.

The cork would of course be used as bottle stoppers, which might be used in bottling of various beverages. Cork itself is also used in floor/wall panels with [various different patterns](https://www.google.com/search?q=cork+floor+tiles&client=firefox-b-d&source=lnms&tbm=isch&sa=X&ved=0ahUKEwifmvKYiujhAhXaWxUIHfYCAJIQ_AUIDigB&biw=1680&bih=936#imgrc=_). A slab of cork would be awesome to have.

https://en.wikipedia.org/wiki/Quercus_suber
https://en.wikipedia.org/wiki/Cork_(material)

**Comment by DWX12** [comment]
Should be similar to Harvestcraft's special trees that players harvest the bark from. A player could strip the bark and it would regrow overtime, much like how real processing of cork is done.

How about a cork boat too. Could give extra speed to that boat just because it would be super buoyant.

**Comment by Syndaryl** [comment]
Cork floor/wall panels with interesting patterns sounds like a chance for Chisel integration.

**Comment by Alatyami** [comment]
At this time, we're not going to implement "cork planks". At this time, it is just going to be for materials.
