### ISSUE TITLE
Add standard colors for bees wax.

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.12#178]
Add all 16 colors for bees wax. Some wax will not be used until later when we add candles or different colors for sealing cheeses.

**Comment by Syndaryl** [comment]
Are they interchangeable with the coloured waxes from Harvestcraft and Quark?

**Comment by Alatyami** [comment]
Will need to check, but long as they use the EnumDye they will be.

**Comment by Alatyami** [comment]
Recipes are in place.
