### ISSUE TITLE
Disable worldgen lag log

### ISSUE THREAD

**Issue by kungfunick123** [GrowthcraftCE/Growthcraft-1.12#198]
I get an error exploring saying growthcraft loaded a new chunk and it caused cascading worldgen lag. Presumably this is because my server doesn't quite have enough resources but it hasn't caused noticeable issue. It says that log can be disabled in the Forge config and I found the growthcraft core config but it just says S:log_level=info. What do I change it to so that log will stop showing up?

**Comment by Alatyami** [comment]
You'll need to change the log level of Forge itself. I'll get you the syntax when I get to a desktop.

**Comment by Alatyami** [comment]
In your config folder, create a file called "logging.properties" and add the following line:

conf/logging.properties
`.level=ERROR`

Keep in mind that this will only affect the log files which will decrease your File I/O. The console logging is actually hard coded by Forge.

Reference: https://www.minecraftforge.net/forum/topic/10474-how-to-set-up-my-logger/

**Comment by kungfunick123** [comment]
Alrighty, thank you. I know it won't get rid of everything, it just says that portion of it can be taken out and that's the only thing that shows up as frequently as it does since I have 5 people on exploring a bunch
