### ISSUE TITLE
Game crashed after eating gold apple and drinking wine

### ISSUE THREAD

**Issue by gohansaiya** [GrowthcraftCE/Growthcraft-1.12#20]
crash report:
[crash-2018-07-15_22.05.09-server.txt](https://github.com/GrowthcraftCE/Growthcraft-1.12/files/2195759/crash-2018-07-15_22.05.09-server.txt)

**Comment by Avatair** [comment]
Seems that something gets broken on attempt to update minecraft statistics.

**Comment by Alatyami** [comment]
Tested with Growthcraft 4.0.4.300 and cannot duplicate. There might be a conflict with another mod. This issue has been stale for a very long time. If it is still an issue, please let us know.
