### ISSUE TITLE
Cheese causes crash

### ISSUE THREAD

**Issue by BlueCreeper160** [GrowthcraftCE/Growthcraft-1.12#219]
I've made cheese and when I tried to convert it into slices with right-clicking vanillafix send me a notification about growthcraft rice ran into a problem, here's the crash report:
[crash-2019-07-21_20.09.47-server.txt](https://github.com/GrowthcraftCE/Growthcraft-1.12/files/3415314/crash-2019-07-21_20.09.47-server.txt)

**Comment by Alatyami** [comment]
What does vanilla fix do? If you disable it, do you still crash?

**Comment by Avatair** [comment]
It is a crash when GC checks if the held item is valid for slicing a cheese wheel. I'll check it after work.
