### ISSUE TITLE
Growthcraft Rice: rice paddy not working

### ISSUE THREAD

**Issue by lysinelai** [GrowthcraftCE/Growthcraft-1.12#224]
When I right click a farmland with a shovel, nothing happens. This happens even if I only have Growthcraft installed.

**Comment by Alatyami** [comment]
In Growthcraft 4 this was change to use the cultivator instead due to a conflict with another mod that also used the shovel. The cultivator is crafted using two sticks and three iron nuggets. Pointing like an arrow to the upper left of the craft ing grid.
