### ISSUE TITLE
Having trouble with brewing Hopped, Lagered, Fermented Ale

### ISSUE THREAD

**Issue by Tschipp** [GrowthcraftCE/Growthcraft-1.12#229]
So I tried to make Hopped, Lagered, Fermented Ale, seeing as it has great stats.
I found no information on the web on how to make it, so I checked out the config and found the recipes there.
I am assuming that Hopped, Lagered, Fermented Ale is `fluid_booze_hopale_lager`.

According to `fermenting.json`:
`fluid_booze_hopale_lager` is made by fermenting `fluid_booze_hopale_hyperextended` with Lager Yeast. 
`fluid_booze_hopale_hyperextended` is made by fermenting `fluid_booze_hopale_potent` with Ethereal Yeast.
`fluid_booze_hopale_potent` is made by fermenting `fluid_booze_hopale_normal` with Glowstone Dust.
`fluid_booze_hopale_normal` is made by fermenting `fluid_booze_hopale_unhopped` with either Nether Wart or Brewers Yeast.

According to `brewing.json`:
`fluid_booze_hopale_unhopped` is made by brewing `fluid_booze_hopale_young` with Hops.
`fluid_booze_hopale_young` is made by brewing water with Wheat.

Phew... quite a process. Sadly, it doesn't seem to work for me.
I brew water with wheat and then with hops to get `fluid_booze_hopale_unhopped`.
I then also fermented it by using Nether Wart.
But when I try to add glowstone dust to the `fluid_booze_hopale_normal`, it just turns into `fluid_booze_hopale_normal` again! (Or at least it seems so to me, it just says "Fermented" when hovering over it).

Am I missing something important here?

**Comment by Avatair** [comment]
Could be a bug in the recipe as adding an ingredient should always change the booze type. We'll check it.

**Comment by Tschipp** [comment]
thank you

**Comment by Tschipp** [comment]
Do we have an update on this?

**Comment by Alatyami** [comment]
Can you test 4.1.3? 

https://www.curseforge.com/minecraft/mc-mods/growthcraft-community-edition/files/2892715

**Comment by Tschipp** [comment]
Yes, sorry that I've been so unresponsive but I've been preoccupied with real live and COVID-19 lol

**Comment by Avatair** [comment]
This topic with COVID-19 is impacting everybody today. In Germany we will work in Home Office beginning next week. And schools are closed for children.

**Comment by Alatyami** [comment]
Closing out due to inactivity. All of our testing with 4.1.3+ has everything working. Let us know if you are still having issues.

**Comment by Tschipp** [comment]
Will do
