### ISSUE TITLE
Server crash while player use the rope

### ISSUE THREAD

**Issue by zch12138** [GrowthcraftCE/Growthcraft-1.12#23]
Hello, I am hosting a server with sponge1.12.2-3361 and forge-2705, when my player put the rope to the fence. The server is crash. Could you fix it please?
Here is the crash report
[crash-2018-08-18_20.44.24-server.txt](https://github.com/GrowthcraftCE/Growthcraft-1.12/files/2299536/crash-2018-08-18_20.44.24-server.txt)

**Comment by Alatyami** [comment]
From what I can tell, this is specific to SpongeForge, not sure if it is an issue on their end or ours. 

Looks like it is actually on their end. SpongeForge is getting into an infinite loop. From your log, Sponge calls getSpongeData on the TileEntityRopeKnot.getTileData(), TERK.getTileData() returns the compound tagged Inventory. SpongeForge doesn't like that and calls getTileData() again and again, until it crashes.

TileEntityRopeKnot still extends TileEntity and not GrowthcraftTileInventoryBase. 

I'll add this to the backlog.

**Comment by zch12138** [comment]
thank you ^ ^
