### ISSUE TITLE
Brewing Kettle middle Slot is locked

### ISSUE THREAD

**Issue by RandyBatista61** [GrowthcraftCE/Growthcraft-1.12#237]
[
![Brewing With Kettle Lid](https://user-images.githubusercontent.com/16107577/62795248-5a115900-baa4-11e9-8197-4b8da66f7bde.gif)
![Brewing Without Kettle Lid](https://user-images.githubusercontent.com/16107577/62795250-5d0c4980-baa4-11e9-80ce-e6681d6a870e.gif)

](url)

Growthcraft version 4.0.5.300:
I added the water into the Brewing Kettle, the brewing kettle lid onto the left slot, and placed netherrack with fire below the kettle to set the water to boil, but when I try to insert ingredients in the middle slot I can't get it in. The middle slot is locked either with and without the Brewing Kettle Lid.

**Comment by RandyBatista61** [comment]
[

](url)

**Comment by Alatyami** [comment]
@RandyBatista61 did you self fix the issue?

**Comment by RandyBatista61** [comment]
[
![ezgif-5-baf313b7e468](https://user-images.githubusercontent.com/16107577/62796268-d4db7380-baa6-11e9-8712-f7d4e2b1db28.gif)
](url)
I thought I did but it still not working. Sorry for accidentally closing it

**Comment by Avatair** [comment]
It usually checks the recipes to only allow valid ingredients. Did you try to delete the growthcraft config subfolder in order to reset the recipes?

**Comment by RandyBatista61** [comment]
I haven't touch the mod file

**Comment by Avatair** [comment]
The mod file itself should be unrelated to it. There is a subfolder in the config folder for growthcraft, which is created on first launch of the mod. Try to delete it. It will be recreated but with new recipes.

**Comment by RandyBatista61** [comment]
It is working now. Thanks a lot for the help

**Comment by Avatair** [comment]
You're welcome
