### ISSUE TITLE
Fermentation Barrel: Progress ToolTip incorrectly renders

### ISSUE THREAD

**Issue by Alatyami** [GrowthcraftCE/Growthcraft-1.12#26]
Version: 4.0.3.200

The progress arrow renders as "gui.grc.progress.format" instead of the actual progress.

![2018-08-21_00 09 19](https://user-images.githubusercontent.com/1868411/44379954-794f5900-a4d6-11e8-8e70-67be1f620dc2.png)

**Comment by Avatair** [comment]
This is a missing translation issue.
