### ISSUE TITLE
[request] ability specify nbt tag in config output_fluid

### ISSUE THREAD

**Issue by nephatrine** [GrowthcraftCE/Growthcraft-1.12#268]
Would like to add ability to ferment a couple of Rustic alcohols using the fermentation barrels and so was looking to add an iron wine fermentation recipe, but the fluids from that mod rely on an NBT tag to mark the "quality" of the batch and I don't see any way to specify something like that in the fluid json schema currently. Would be neat functionality to have for other things as well possibly like a custom modpack that allows "fermenting" resonating crystal liquid from Deep Resonance as an alternate method of refining it.

**Comment by Alatyami** [comment]
This will be possible after we revamp the recipes to standard json.

**Comment by Alatyami** [comment]
This will actually require a significant change to the fermenting code. In MC 1.15 we are completely changing how the fermentation process is coded. If possible we'll back-port to 1.12.
