### ISSUE TITLE
No Cultivator to be found; Rice not possible to harvest

### ISSUE THREAD

**Issue by Burgersim** [GrowthcraftCE/Growthcraft-1.12#273]
Hi there, in the newest Version of this mod 4.1.0 for MC 1.12.2 I can't seem to find the cultivator to make rice patties to plant the rice crops.

I also wanted to suggest maybe making the rice harvestable differently, you could change it so that the crop needs to be in a water block (waterlogged) and have a block of air above, that would kinda look like natural ricefields and the neet for a tool and a different farmland would be gone.

![2019-10-24_17 02 37](https://user-images.githubusercontent.com/26793150/67498663-1e883300-f680-11e9-9aa0-ba59b64c4e08.png)

**Comment by Burgersim** [comment]
![2019-10-24_17 42 13](https://user-images.githubusercontent.com/26793150/67502116-b1779c00-f685-11e9-8c2c-ebf45467d183.png)

This is what I get. Just thinking, could it have sthg to do with tinkers construct or tinkered hegemony (which replaces vanilla tools in recipes with tinker variants for consistency)? On what tool is the cultivator based?

**Comment by Alatyami** [comment]
It's and extended hoe. That might be the case.

**Comment by Burgersim** [comment]
ok i disabled tinkered hegemony and now there's the cultivator... good to have it, but not so good for my modpack, I need tinkered hegemony to disable the vanilla tools... could making the patty word with sthg different, like sthg from tinkers construct, that extends the hoe class?

**Comment by Syndaryl** [comment]
@Burgersim - set up Tinkers Hegmony to not ban it.
Then use CraftTweaker to set up an alternate crafting recipe to your liking.

**Comment by Burgersim** [comment]
@Syndaryl thx for the suggestion ^^

**Comment by Alatyami** [comment]
After much thought on this, we are not going to deviate from extending ItemHoe. The Cultivator is an extension of the vanilla hoe, and I do not see us duplicating all of the ItemHoe for this.
