### ISSUE TITLE
Rice Paddies do not immediately fill

### ISSUE THREAD

**Issue by katubug** [GrowthcraftCE/Growthcraft-1.12#274]
I discovered this while running a limited modlist (seen in the first 2 screenshots), but I was able to replicate it in an instance with only GrowthCraft (third screenshot).

I am using growthcraft-1.12.2-4.1.0. and forge 14.23.5.2847.

When I right click farmland with a cultivator, it does not flood, as you can see in the debug info. I waited a few minutes, and even toggled downfall (idk, seemed valid at the time haha), but no luck. It was suggested that I try using one water source and multiple paddies, but unfortunately the issue persisted. I also created a new world, just in case that was an issue somehow.

Then, for the final screenshot, I removed all other mods and also created a new world, and experienced the same issue.

![2019-10-29_22 08 28](https://user-images.githubusercontent.com/20935286/67826565-ec6d3b80-fa9a-11e9-8753-c7ba87eb6f24.png)
![2019-10-29_22 11 44](https://user-images.githubusercontent.com/20935286/67826566-ec6d3b80-fa9a-11e9-867e-1eda3837aaa8.png)
![2019-10-29_22 19 58](https://user-images.githubusercontent.com/20935286/67826567-ed05d200-fa9a-11e9-9d0d-601f271a2462.png)

Nothing appears in my latest.log or debug.log when I right click to create the paddy, but if desired I can send you them anyway.

Thanks for your help!

**Comment by Alatyami** [comment]
I have been trying to duplicate this bug and I cannot.

**Comment by katubug** [comment]
I went to go replicate so I could upload the world file for you, but it is mysteriously now working, even in the exact environment in which it originally occurred. So it was probably either user error on my part, or modded minecraft being modded minecraft. Thanks for looking into it, and I apologize for taking up your time!

**Comment by Alatyami** [comment]
No problem. It could have also been tick latency.
