### ISSUE TITLE
Red grape seeds not dropping

### ISSUE THREAD

**Issue by ArtOfCombat** [GrowthcraftCE/Growthcraft-1.12#285]
I have broken dozens if not hundreds of vines and have yet to find a single red grape seed. Am I missing a piece of information?

**Comment by Alatyami** [comment]
Which version of growthcraft are you using?

**Comment by ArtOfCombat** [comment]
4.1.0, the latest available. The pack is Mythic Novus [Kinetic]. I am on SP.

**Comment by darthvader45** [comment]
I'd use 4.1.1, as that was released on Github, and should be on CurseForge.

**Comment by Alatyami** [comment]
Did some testing .... There is a 1 in 10 chance to drop a variation of grape seed. Important thing to note is that you cannot be using shears.

**Comment by ArtOfCombat** [comment]
I got 40 of purple and green... No red. :\

**Comment by Alatyami** [comment]
That's good information .... found the bug. 

`
int randomGrapeSeed = random.nextInt(GrapeTypes.values().length - 1);
GrapeTypes grapeTypes = GrapeTypes.values()[randomGrapeSeed];
`

There are three grape types, so the nextInt actually results in a random number from 0 inclusive to 2 exclusive. So GrapeTypes.values()[2] actually will never happen and that is the Red Grapes.
