### ISSUE TITLE
4.1.1 changelog?

### ISSUE THREAD

**Issue by xJon** [GrowthcraftCE/Growthcraft-1.12#286]
Hi,
Is there any changelog for this release?
https://www.curseforge.com/minecraft/mc-mods/growthcraft-community-edition/files/2838197
Thanks!

**Comment by darthvader45** [comment]
https://github.com/GrowthcraftCE/Growthcraft-1.12/releases has all the info you need.  Though, yeah, it could use being put onto CurseForge.

**Comment by xJon** [comment]
I've already checked that page out but there's no changelog for `4.1.1`, only for `4.1.1.100` & `4.1.1.200`

**Comment by darthvader45** [comment]
Both are part of the 4.1.1 release.

**Comment by xJon** [comment]
I see. Thank you!

**Comment by darthvader45** [comment]
Np
