### ISSUE TITLE
4.1.0 Can't find thistle

### ISSUE THREAD

**Issue by ArtOfCombat** [GrowthcraftCE/Growthcraft-1.12#289]
I can't find thistles by any means in 4.1.0. Just making you aware in case this WASN'T fixed in 4.1.1.

**Comment by Alatyami** [comment]
They are added to the Grass loot table. They do not naturally spawn in the world.

**Comment by ArtOfCombat** [comment]
Wiki says otherwise, but I believe you. However, breaking grass does NOT drop thistle seeds in this pack, as far as I can tell. Is there a reason this might be?

**Comment by ArtOfCombat** [comment]
Bewitchment seeds drop fine.

**Comment by Alatyami** [comment]
It's an official bug now .... jsut checked the source and thistle isn't in any of the loot tables. Should be fixed this weekend.
