### ISSUE TITLE
Asiago Cheese not working?

### ISSUE THREAD

**Issue by ArtOfCombat** [GrowthcraftCE/Growthcraft-1.12#291]
2 salt goes in the cheese vat just fine, but it won't accept a yellow dye afterwards.

**Comment by Alatyami** [comment]
I just tested it and it works fine. Which version are you running?

**Comment by ArtOfCombat** [comment]
4.1.0

**Comment by Alatyami** [comment]
Is it vanilla yellow dye?

**Comment by Alatyami** [comment]
And just to confirm ..... 

1. 5 Buckets of Milk + Bottle of Rennet + Starter Culture, hit it with a wooden sword. 
2. Waiting for it to turn colors
3. Remove the whey
4. Add the two salt + yellow dye

**Comment by ArtOfCombat** [comment]
Yep. I used the same mix to make gouda after removing the salt.

**Comment by Alatyami** [comment]
Well, not sure that is going on then. I cannot reproduce the issue and Cheese doesn't use the config recipes.

**Comment by Alatyami** [comment]
Looks like we didnt confirm your bug ... 

Sounds like the config recipes are out of sync. Delete your config/growthcraft directory and if you are still having issues, let us know. We still cannot duplicate the issue.
