### ISSUE TITLE
Rock Salt Ore still generates when disabled in config

### ISSUE THREAD

**Issue by xJon** [GrowthcraftCE/Growthcraft-1.12#300]
![Screenshot_2](https://user-images.githubusercontent.com/8945347/72563248-ecb8ee00-38b5-11ea-9814-18d06274a047.png)
![Screenshot_1](https://user-images.githubusercontent.com/8945347/72563250-ed518480-38b5-11ea-8160-15663acb1dda.png)

Any idea why? Thanks!

**Comment by Alatyami** [comment]
can you confirm which which version you are using?

**Comment by xJon** [comment]
Oh yes sorry.
`GalacticraftCore-1.12.2-4.0.2.243`.

**Comment by xJon** [comment]
Changing `I:blockSaltOreChanceToSpawn` to `=0` does not help either.

**Comment by Alatyami** [comment]
We're looking into it ... a take a minute

**Comment by xJon** [comment]
No worries. Thank you!

**Comment by xJon** [comment]
Hi, is there going to be any update soon?
(I'm thinking whether I should wait with a pack update)

**Comment by Alatyami** [comment]
It'll be released in 4.1.2.200 later this week.

**Comment by xJon** [comment]
@Alatyami Thank you!

**Comment by xJon** [comment]
@Alatyami Any chance you can release the fix?

**Comment by Alatyami** [comment]
We are working out a NullPointer exception that popped up.

**Comment by xJon** [comment]
Okay, thank you
