### ISSUE TITLE
Adding Growthcraft to a modpack, here's the modlist

### ISSUE THREAD

**Issue by blutec-dev** [GrowthcraftCE/Growthcraft-1.12#312]
Dear Growthcraft CE Team, [as requested](https://github.com/GrowthcraftCE/Growthcraft-1.12#license), here is the modlist for a modpack that I am planning to make public (on Curseforge):

| **Mod**                                             | **Author/owner**     |
|-----------------------------------------------------|----------------------|
| A Block of Charcoal                                 | Turkey2349           |
| Actually Additions                                  | Ellpeck              |
| Advancement Book                                    | ParkerMc01           |
| Akashic Tome                                        | Vazkii               |
| Animania                                            | Purplicious_Cow      |
| Antique Atlas                                       | Hunternif            |
| Apathetic Mobs                                      | whizzball            |
| AppleCore                                           | squeek502            |
| Aquaculture 2                                       | Shadowclaimer        |
| Aroma1997Core                                       | Aroma1997            |
| Aroma1997s Dimensional World                        | Aroma1997            |
| AromaBackup                                         | Aroma1997            |
| Atlas Extras                                        | Rikshy               |
| Auto Third Person                                   | quat1024             |
| AutoPlant                                           | Lemonszz             |
| AutoRegLib                                          | Vazkii               |
| Backpacks                                           | Eydamos              |
| Bark Books                                          | oneandonlyflexo      |
| BasketCase                                          | TheDaeruin           |
| Baubles                                             | Azanor13             |
| Bed Patch                                           | Mordenkainen3141     |
| Better Advancements                                 | way2muchnoise        |
| Better Animals Plus                                 | cybercat5555         |
| Better Diving                                       | meldexun             |
| Better Foliage                                      | octarine_noise       |
| Better Placement                                    | tterrag1098          |
| BetterFps                                           | Guichaguri           |
| BiblioCraft                                         | Nuchaz               |
| Biome Bundle                                        | mc_pitman            |
| Biome Staff                                         | TheRealp455w0rd      |
| Birds Nests                                         | cleverpanda714       |
| Bonsai Trees 2                                      | davenonymous         |
| Bookshelf                                           | DarkhaxDev           |
| Bookworm                                            | SoggyStache          |
| Botania                                             | Vazkii               |
| Bring Me The Rings!                                 | zabi94               |
| Camera Mod                                          | henkelmax            |
| Camera Obscura                                      | RazzleberryFox       |
| Carry On                                            | Tschipp              |
| Chameleon                                           | Texelsaur            |
| Charm                                               | svenhjol             |
| Chest Transporter                                   | cubex2               |
| Chicken Chunks 1.8.+                                | covers1624           |
| Chisel                                              | tterrag1098          |
| Chunk Animator                                      | Lumien231            |
| Clarity                                             | EpicSquid319         |
| Client Tweaks                                       | BlayTheNinth         |
| Clumps                                              | Jaredlll08           |
| CodeChicken Lib 1.8.+                               | covers1624           |
| CoFH Core                                           | TeamCoFH             |
| CoFH World                                          | TeamCoFH             |
| Comforts                                            | TheIllusiveC4        |
| Compact Drawers                                     | samtrion             |
| ConnectedTexturesMod                                | tterrag1098          |
| Controllable                                        | MrCrayfish           |
| Controlled Burn                                     | laike_endaril        |
| Controlling                                         | Jaredlll08           |
| Cooking for Blockheads                              | BlayTheNinth         |
| Corail Recycler                                     | Corail_31            |
| CoralReef                                           | primetoxinz          |
| Cosmetic Armor Reworked                             | LainMI               |
| CraftingCraft                                       | BlayTheNinth         |
| CraftingNetherStar                                  | zeck_g               |
| CraftStudio API                                     | ZeAmateis            |
| CraftTweaker                                        | Jaredlll08           |
| CTD Core                                            | TheMasterGeneral     |
| Dawn Of Time - Builder Edition                      | dawnoftime_team      |
| Death Compass                                       | vadis365             |
| Decocraft                                           | RazzleberryFox       |
| Display                                             | Martacus             |
| Dooglamoo Jr. Archaeology                           | Dooglamoo            |
| Dooglamoo Painter Mod                               | Dooglamoo            |
| Double Slabs                                        | CJMinecraft01        |
| Dynamic Lights                                      | atomicstrykergrumpy  |
| Dynamic Surroundings                                | OreCruncher          |
| Dynamic Surroundings: HUDs                          | OreCruncher          |
| Earthworks                                          | Alsender\_           |
| Enchantment Descriptions                            | DarkhaxDev           |
| Ender IO Base                                       | HenryLoenwind        |
| Ender IO Conduits                                   | HenryLoenwind        |
| Ender IO Machines                                   | HenryLoenwind        |
| Ender IO RS Conduits                                | HenryLoenwind        |
| Ender IO TiC                                        | HenryLoenwind        |
| Ender Storage 1.8.+                                 | covers1624           |
| EnderCore                                           | tterrag1098          |
| Engineer's Decor                                    | wilechaote           |
| Engineer's Doors                                    | nihiltres            |
| Exotic Birds                                        | ThePavoReality       |
| Extra Utilities                                     | RWTema               |
| Facade Painter                                      | MCLathanael          |
| Fairy Lights                                        | pau101               |
| Familiar Fauna                                      | Forstride            |
| Farming for Blockheads                              | BlayTheNinth         |
| Farseek                                             | delvr                |
| Fast Leaf Decay                                     | olafskiii            |
| Faster Ladder Climbing                              | maddachshund         |
| FastFurnace                                         | Shadows_of_Fire      |
| FastWorkbench                                       | Shadows_of_Fire      |
| Fence Jumper                                        | TheRealp455w0rd      |
| Ferdinand's Flowers                                 | c0_0ry               |
| FindMe                                              | Buuz135              |
| FoamFix​                                             | asiekierka           |
| Friendly Fire                                       | DarkhaxDev           |
| FTB Library                                         | LatvianModder        |
| Fullscreen Windowed (Borderless) for Minecraft      | hancin               |
| Future Versions                                     | TipTopGamingOfficial |
| Garden Stuff                                        | Texelsaur            |
| Gas Conduits                                        | pupnewfster          |
| Gauges and Switches                                 | wilechaote           |
| Growthcraft Community Edition                       | Alatyami             |
| Guidebook                                           | gigaherz             |
| Hat Stand                                           | ohaiiChun            |
| Hats                                                | ohaiiChun            |
| Hopper Ducts                                        | FyberOptic           |
| Hunger In Peace                                     | squeek502            |
| Hunger Overhaul                                     | ProgWML6             |
| Hunting Dimension                                   | DarkhaxDev           |
| iChunUtil                                           | ohaiiChun            |
| Immersive Engineering                               | BluSunrize           |
| Immersive Petroleum                                 | Flaxbeard            |
| Immersive Posts                                     | TwistedGate          |
| Immersive Technology                                | tgstyle0             |
| Inspirations                                        | KnightMiner          |
| InstantUnify                                        | KidsDontPlay         |
| Interaction Wheel                                   | McJty                |
| Inventory Sorter                                    | cpw                  |
| Inventory Tweaks                                    | JimeoWan             |
| Iron Chests                                         | ProgWML6             |
| ItemZoom                                            | mezz                 |
| IvToolkit                                           | Ivorforce            |
| JEI Integration                                     | SnowShock35          |
| JEI Villagers                                       | Buuz135              |
| JourneyMap                                          | techbrew             |
| Just a Few Fish                                     | Tmtravlr             |
| Just A Raft Mod                                     | Mrbysco              |
| Just Enough BrewCraft (JEBC)                        | mrAppleXZ            |
| Just Enough Calculation                             | towdium              |
| Just Enough HarvestCraft (JEHC)                     | mrAppleXZ            |
| Just Enough Items (JEI)                             | mezz                 |
| Just Enough Pattern Banners                         | Lorexe               |
| Just Enough Petroleum                               | BordListian          |
| Keyboard Wizard                                     | mrnerdy42            |
| KleeSlabs                                           | BlayTheNinth         |
| Lapis Stays in the Enchanting Table                 | csb987               |
| Linking Through the Ages (LTTA)                     | IAmTheFloydman       |
| linking-tweaks                                      | Veovis_Muaddib       |
| LLibrary                                            | \_ForgeUser11902522  |
| MalisisBlocks                                       | Ordinastie           |
| MalisisCore                                         | Ordinastie           |
| MalisisDoors                                        | Ordinastie           |
| MalisisSwitches                                     | Ordinastie           |
| Mantle                                              | mDiyo                |
| McJtyLib                                            | McJty                |
| Mekanism                                            | bradyaidanc          |
| Mekanism Generators                                 | bradyaidanc          |
| Mekanism Tools                                      | bradyaidanc          |
| MekanismOres                                        | phantamanta44        |
| MineMenu                                            | Girafi               |
| Mo' Glowstone                                       | TheMasterGeneral     |
| Moar Boats                                          | jglrxavpok           |
| Mod Name Tooltip                                    | mezz                 |
| ModTweaker                                          | Jaredlll08           |
| More Cauldrons                                      | Mrbysco              |
| More Mystcraft                                      | IAmTheFloydman       |
| Morph-o-Tool                                        | Vazkii               |
| Mouse Tweaks                                        | YaLTeR               |
| MrCrayfish's Furniture Mod                          | MrCrayfish           |
| MTLib                                               | Jaredlll08           |
| Mystcraft                                           | XCompWiz             |
| mystcraft-info                                      | Veovis_Muaddib       |
| Mystical Wildlife                                   | Lykrast              |
| Mystical World                                      | EpicSquid319         |
| MysticalLib                                         | EpicSquid319         |
| Nature's Compass                                    | Chaosyr              |
| Nibbler                                             | oneandonlyflexo      |
| NoFov                                               | Lumien231            |
| Nomadic Tents                                       | skyjay1              |
| Not Enough Pets                                     | AstroTibs            |
| NotEnoughIDs                                        | fewizz\_             |
| Ocean Floor - Clay Sand and Dirt                    | Lothrazar            |
| Oops! - Undo                                        | darkevilmac          |
| Open Terrain Generator (OpenTerrainGenerator / OTG) | team_otg             |
| OpenBlocks                                          | OpenMods             |
| OpenEye                                             | OpenMods             |
| OpenModsLib                                         | OpenMods             |
| Ore Control                                         | masady               |
| OreLib                                              | OreCruncher          |
| Outfox                                              | ItsTheKais           |
| Pages                                               | IAmTheFloydman       |
| Paintings ++                                        | AbsolemJackdaw       |
| Pam's BrewCraft                                     | pamharvestcraft      |
| Pam's HarvestCraft                                  | pamharvestcraft      |
| Patchouli                                           | Vazkii               |
| Photoptics                                          | jriwanek             |
| PizzaCraft                                          | tiviacz1337          |
| Placebo                                             | Shadows_of_Fire      |
| Plants                                              | Shadows_of_Fire      |
| Potion Fingers                                      | Vazkii               |
| PTRLib                                              | RazzleberryFox       |
| Quark                                               | Vazkii               |
| Quark Oddities                                      | Vazkii               |
| Random Things                                       | Lumien231            |
| Recurrent Complex                                   | Ivorforce            |
| Redstone Flux                                       | TeamCoFH             |
| Refined Storage                                     | raoulvdberge         |
| Refined Storage Addons                              | raoulvdberge         |
| RFTools                                             | McJty                |
| Roots                                               | EpicSquid319         |
| Rustic                                              | mangoose3039         |
| Save My Stronghold!                                 | YUNGNICKYOUNG        |
| Scannable                                           | Sangar\_             |
| Shadowfacts' Forgelin                               | ShadowfactsDev       |
| Signpost                                            | Gollorum             |
| Simple Storage Network                              | Lothrazar            |
| SimpleZoom                                          | UnRealDinnerbone     |
| Smart HUD                                           | HeckinChloe          |
| Smooth Scrolling Everywhere (Forge)                 | shedaniel            |
| Snow! Real Magic!                                   | Snownee\_            |
| Sophisticated wolves                                | nightkosh            |
| Sound Filters                                       | Tmtravlr             |
| Spice of Life: Carrot Edition                       | lordcazsius          |
| Statues                                             | ShyNieke             |
| Stellar API                                         | jriwanek             |
| Stellar Sky                                         | jriwanek             |
| stimmedcow : NoMoreRecipeConflict                   | GotoLink             |
| Storage Drawers                                     | Texelsaur            |
| Storage Drawers Unlimited                           | raptor4694           |
| Streams                                             | delvr                |
| SwingThroughGrass                                   | exidex               |
| The Birdwatching Mod                                | ikerleon02           |
| The Disenchanter Mod                                | impelon              |
| The One Probe                                       | McJty                |
| Thermal Cultivation                                 | TeamCoFH             |
| Thermal Dynamics                                    | TeamCoFH             |
| Thermal Expansion                                   | TeamCoFH             |
| Thermal Foundation                                  | TeamCoFH             |
| Tinkers Construct                                   | mDiyo                |
| Tinker's JEI                                        | Possible_triangle    |
| TipTheScales                                        | Jaredlll08           |
| Toast Control                                       | Shadows_of_Fire      |
| Tomb Many Graves 2                                  | M4thG33k             |
| Tool Belt                                           | gigaherz             |
| TOP Addons                                          | DrManganese          |
| Totemic                                             | ljfa2                |
| Trample Stopper                                     | UnRealDinnerbone     |
| TrashSlot                                           | BlayTheNinth         |
| Traveller's Backpack                                | tiviacz1337          |
| Tumbleweed                                          | konwboj              |
| UniDict                                             | WanionCane           |
| Uppers                                              | vadis365             |
| Useful Interior                                     | ostpol               |
| VanillaFoodPantry Mod [FORGE]                       | The_Wabbit0101       |
| Village Names                                       | AstroTibs            |
| Villager Market                                     | face_of_cat          |
| Waddles                                             | Girafi               |
| WAIM - What am I missing?                           | Jaredlll08           |
| Wall-Jump! [FORGE]                                  | genandnic            |
| WanionLib                                           | WanionCane           |
| Water Strainer                                      | Ruuubi               |
| Waystones                                           | BlayTheNinth         |
| What's That Slot?                                   | gegy1000             |
| WholeTreeAxe                                        | cubex2               |
| Wings                                               | pau101               |
| Wolf Armor and Storage                              | satyrnidae           |
| XP From Harvest                                     | ReaIGecko            |
| YABBA                                               | LatvianModder        |
| YUNG's Better Caves                                 | YUNGNICKYOUNG        |

**Comment by Alatyami** [comment]
A lot of good mods in there .... let us know if you run into any compatibility issues.
