### ISSUE TITLE
Config Honey disabled crash

### ISSUE THREAD

**Issue by AngelWing314** [GrowthcraftCE/Growthcraft-1.12#313]
The game wont start up when  B:enableHoney is set to false in the config. It just results in a crash. I'll leave the crash log in the attachment. Hope it helps locating the problem.
[crash-2020-02-22_11.32.17-client.txt](https://github.com/GrowthcraftCE/Growthcraft-1.12/files/4239164/crash-2020-02-22_11.32.17-client.txt)

**Comment by Alatyami** [comment]
We'll get this fixed in the next release.
