### ISSUE TITLE
Can't produce rennet

### ISSUE THREAD

**Issue by xJon** [GrowthcraftCE/Growthcraft-1.12#316]
As reported over https://github.com/xJon/The-1.12.2-Pack/issues/200, and following the online information, combining water with stomach/thistle in a heated Brew Kettle does not produce rennet.
![Screenshot_2](https://user-images.githubusercontent.com/8945347/75183489-577a0680-574b-11ea-9b51-4b263aee8c72.png)

**Comment by Alatyami** [comment]
Not sure how you got the water into the right tank ..... hit the toggle arrows to move the water to the left "input" tank.

**Comment by xJon** [comment]
@Alatyami I did, it was there initially, and didn't do anything either.
I moved the waters between the tanks hoping something would happen.
The screenshot with the water on the left is coincidental.

**Comment by Alatyami** [comment]
In that case, need to check the config files. 

config/growthcraft/cellar/brewing.json

By default the first entry is the recipe for rennet. It is based on the ore dictionary of "rennetSource". We set the oreDictionary to include the following:

GrowthcraftMilkItems.thistle
GrowthcraftMilkItems.stomach
RusticModBlocks.windThistle

To reset the config file, the user reporting the issue can delete the config file and it will rebuild when the game is restarted.

**Comment by Alatyami** [comment]
@xJon Are there other mods installed that might be changing the ore dictionary entries? 

As a test, you could add the following the config file:

`
{
      "comment": "",
      "item": {
        "ore": null,
        "comment": "",
        "mod_id": "growthcraft_milk",
        "name": "thistle",
        "amount": 1,
        "meta": 0
      },
      "input_fluid": {
        "comment": "Water",
        "name": "water",
        "amount": 1000
      },
      "output_fluid": {
        "comment": "Rennet",
        "name": "fluid_rennet",
        "amount": 1000
      },
      "residue": {
        "pomace": 0.0,
        "ore": null,
        "comment": "Bone Meal",
        "mod_id": "minecraft",
        "name": "dye",
        "amount": 1,
        "meta": 15
      },
      "requiresLid": false,
      "time": 1200
    }
`

**Comment by xJon** [comment]
As written [here](https://github.com/xJon/The-1.12.2-Pack/issues/200#issuecomment-584493990), resetting the configs does not resolve the issue

**Comment by Alatyami** [comment]
Want me to jump into conversation in https://github.com/xJon/The-1.12.2-Pack/issues/200 ?

**Comment by xJon** [comment]
@Alatyami Yeah sure

**Comment by Alatyami** [comment]
@xJon where might I find the modpack?

**Comment by xJon** [comment]
Technic Launcher - https://www.technicpack.net/modpack/the-1122-pack
Twitch App - https://www.curseforge.com/minecraft/modpacks/the-1122-pack

**Comment by Alatyami** [comment]
We found the issue, working on it today. Will be resolved in 4.1.3

**Comment by Alatyami** [comment]
https://www.curseforge.com/minecraft/mc-mods/growthcraft-community-edition/files/2892715
