### ISSUE TITLE
Crash when adding any "young" alcohols to the culture jar

### ISSUE THREAD

**Issue by JonenGales** [GrowthcraftCE/Growthcraft-1.12#323]
Mod was ran from the 1.12.2 pack (modpack)
 
Actions:
Tried using the culture jar from an online server but the jar would not produce yeast. Then started a single player world and attempted to create yeast using the culture jar. Ended in crash, crash log below.

Link to crash report:
https://paste.dimdev.org/ijoqasagex.mccrash

**Comment by TheTennessee** [comment]
This is the 1.12.2 Pack huh? I had to manually update the pack to get rid of the crash, download the 4.1.3 version and put it in (delete the old .jar). However... I still can't get any yeast from the culture jars.

**Comment by Alatyami** [comment]
Looks like the yeast recipes are missing from the recipe files.

**Comment by Lawiel** [comment]
> This is the 1.12.2 Pack huh? I had to manually update the pack to get rid of the crash, download the 4.1.3 version and put it in (delete the old .jar). However... I still can't get any yeast from the culture jars.

Have pretty much the same issue, I've been using v4.1.3.100, couldn't get any yeast, tried to change all json files, configs, etc. It never helped...
Then I installed v4.1.2 and now I can craft yeast, seems like that's about the newest version, waiting for the fix :)

**Comment by TheTennessee** [comment]
Yeah. I even tried adding it as a culture thing and using heat. Nothing is happening, though I added in the data to the json right. It seems the culture jars are just broken.

**Comment by TheTennessee** [comment]
Okay, nevermind... I have finally got it to work, just in a really odd way. I revisited the culture jars, realized the poison yeast is invalid now, and rechecked my formatting. I can now make yeast, it's just really... strange.

`{
  "comment": "",
  "data": [
    {
      "comment": "",
      "output_item": {
        "ore": null,
        "comment": "Starter Culture",
        "mod_id": "growthcraft_milk",
        "name": "starter_culture",
        "amount": 1,
        "meta": 0
      },
      "input_fluid": {
        "comment": "Skim Milk",
        "name": "fluid_skim_milk",
        "amount": 250
      },
      "required_heat": 0.6,
      "time": 240
    },
    {
      "comment": "",
      "output_item": {
        "ore": null,
        "comment": "Brewers Yeast",
        "mod_id": "growthcraft_cellar",
        "name": "yeast",
        "amount": 1,
        "meta": 0
      },
      "input_fluid": {
        "comment": "Apple Cider",
        "name": "fluid_booze_apple_juice",
        "amount": 250
      },
      "required_heat": 0.3,
      "time": 240
    },
    {
      "comment": "",
      "output_item": {
        "ore": null,
        "comment": "Origin Yeast",
        "mod_id": "growthcraft_cellar",
        "name": "yeast",
        "amount": 1,
        "meta": 4
      },
      "input_fluid": {
        "comment": "Sake Water",
        "name": "fluid_booze_sake_water",
        "amount": 250
      },
      "required_heat": 0.3,
      "time": 240
    },
    {
      "comment": "",
      "output_item": {
        "ore": null,
        "comment": "Lager Yeast",
        "mod_id": "growthcraft_cellar",
        "name": "yeast",
        "amount": 1,
        "meta": 1
      },
      "input_fluid": {
        "comment": "Ale Wort",
        "name": "fluid_booze_hopale_young",
        "amount": 250
      },
      "required_heat": 0.3,
      "time": 240
    },
    {
      "comment": "",
      "output_item": {
        "ore": null,
        "comment": "Ethereal Yeast",
        "mod_id": "growthcraft_cellar",
        "name": "yeast",
        "amount": 1,
        "meta": 3
      },
      "input_fluid": {
        "comment": "Hot Spring Water",
        "name": "hot_spring_water",
        "amount": 250
      },
      "required_heat": 0.3,
      "time": 240
    }
  ]
}
`

**Comment by Alatyami** [comment]
So .... that's not the designed method of getting yeast. Although, you/your server is more than welcome to use it. 

YeastGeneration is actually listed in the yeast.json config file. When the culture jar doesn't have a heat source, it changes to YeastGeneration mode. Yeast generation is listed in the yeast.json file. 

Place any fluid with the BoozeTag.YOUNG tag and it will start producing yeast based on the biome that it is located in.
