### ISSUE TITLE
Rennet error

### ISSUE THREAD

**Issue by Chocolatta** [GrowthcraftCE/Growthcraft-1.12#329]
The rennet creating does not proceed. The use of thistle and stomach does not give effect. Other processes in the brew kettle are OK. Tested on version 4.1.3.100 and 4.1.3.200

Screenchots:

[https://i.imgur.com/3iOGmqT.png](https://i.imgur.com/89xiXsK.png)
[https://i.imgur.com/WCECrbp.png](https://i.imgur.com/WCECrbp.png)
[https://i.imgur.com/SGRz1Pa.png](https://i.imgur.com/SGRz1Pa.png)
[https://i.imgur.com/BgshrZ0.png](https://i.imgur.com/BgshrZ0.png)
[https://i.imgur.com/3iOGmqT.png](https://i.imgur.com/3iOGmqT.png)

**Comment by Alatyami** [comment]
Have you cleared out your brewing.json file? If so, remove your heat source and then put it back.

**Comment by Chocolatta** [comment]
Thank you for your help, cleaning the file helped.
