### ISSUE TITLE
Unable to make Yeast

### ISSUE THREAD

**Issue by Hensikt** [GrowthcraftCE/Growthcraft-1.12#332]
I've been Waiting for a couple of days now but I havent gotten any yeast. I've setup multiple culture jars with Young alcohol of different kinds but there isn't any yeast forming.

Sorry if the English is bad.

**Comment by Alatyami** [comment]
which version of growthcraft are you using?

**Comment by Hensikt** [comment]
1.12.2-4.1.3.100

**Comment by Alatyami** [comment]
Yeast was fixed in 4.1.3.200
