### ISSUE TITLE
Growthcraft Cellar issue

### ISSUE THREAD

**Issue by Adolfester** [GrowthcraftCE/Growthcraft-1.12#335]
When I try to make yeast, it won't let me, literally put all kinds of alcohols in the culture jar, it doesn't create any kind of yeast, Ale, lager, cider, wine nothing works, help

**Comment by Alatyami** [comment]
have you deleted your culturing.json config file?

**Comment by Adolfester** [comment]
> have you deleted your culturing.json config file?

No, I have never messed with the mod files, it only does not work with the yeast because when I put the skim milk if it gives me initial culture, the only thing I did was delete version 4.1.3.100 and download version 4.1.3.200 and later yeast no longer works for me

I don't know what happens to my growthcraft : /

**Comment by Alatyami** [comment]
In the release notes, we put in a notification about the breaking change to the culture recipes. 

> If you are updating from 4.1.2.* you will need to clear your Growthcraft config files as 4.1.3 introduced more configuration options and fixed some brewing, fermenting, and culture jar recipes.

Specifically, you will want to delete the config/growthcraft/cellar/culturing.json file. When you restart the game, it will rebuild and you will get all of the updated recipes for the culture jar.
