### ISSUE TITLE
Shift+Right-clicking an honey comb in Bee Box's GUI crashes the game

### ISSUE THREAD

**Issue by RisingInIris2017** [GrowthcraftCE/Growthcraft-1.12#338]
## Minecraft Version
1.12.2
## Forge Version
1.12.2-14.23.5.2854
## GrowthCraft CE Version
growthcraft-1.12.2-4.1.3.100
## How to reproduce
1. Get a honey comb item in the inventory.
2. Open the Bee Box GUI.
3. Shift+Right-click at the honey comb item.
4. Game crashes.
## Crash report for the bug
https://paste.ubuntu.com/p/s2k2TKKmGY/

This is an annoying issue. I hope that this can be solved.
Thanks a lot in advance!

**Comment by Alatyami** [comment]
already fixed in 4.1.3.200

**Comment by RisingInIris2017** [comment]
> already fixed in 4.1.3.200

Thanks a lot!
