### ISSUE TITLE
Crashes not fixed with 4.2.2

### ISSUE THREAD

**Issue by xJon** [GrowthcraftCE/Growthcraft-1.12#358]
Game crashed upon breaking grape plant with the new version.
Report: https://pastebin.com/MHQVdMNu

**Comment by Alatyami** [comment]
Single player or multi player. Just tested and I'm not able to reproduce it with 4.2.2

**Comment by xJon** [comment]
Single player. As you can see from the crash log I'm using `4.2.2`.

**Comment by Alatyami** [comment]
Just had to double check. We had one report previously that the client had the newer version but not the server.

**Comment by clienthax** [comment]
@Alatyami  manifest is missing the AccessTransformer entry, so it is never applied in production, resulting in these problems.

**Comment by clienthax** [comment]
https://github.com/GrowthcraftCE/Growthcraft-1.12/pull/359

**Comment by Alatyami** [comment]
Doh, must have happen during the refactoring to get it to build again. Thanks!

**Comment by clienthax** [comment]
You can likely revert the previous fix too, as it just does an additional block lookup.

**Comment by Alatyami** [comment]
Uploaded to curse forge, will be available once the file is approved.
