### ISSUE TITLE
[Suggestion] Adding compat with Heat&Climate

### ISSUE THREAD

**Issue by gatoborrachon** [GrowthcraftCE/Growthcraft-1.12#362]
Well, i can't find any issue related to Heat&Climate so i think you don't know about that mod.

sadly i can't test all the mod has, i don't have the enough time right now but just by looking at some 1.7 videos about the original mod i thought: why not adding compat with Heat&Climate? (and maybe IC2 for the hops if this mod does not use OreDicted items)

Heat&Climate adds many things in common, like fermeting drinks, food, kinetic energy (for that press), crops, etc. if you want to give a look at that mod, i recomend to try it, it has a lot of mechanics related to Heat and Climate

**Comment by Alatyami** [comment]
Growthcraft for MC 1.12 is in maintenance mode, meaning we are not adding any new features or compatibility. This is mainly because it is getting harder to get support for Forge 1.12 and we are currently working on a full code rewrite with Growthcraft for 1.15+.

**Comment by gatoborrachon** [comment]
oh, sad to hear that, but i know many places where you can get 1.12 support if you are interested.

also, everything in the 1.12 is functional and documented in the wiki? well, i find it a little unpractical to not have JEI compat, but if everything is in the wiki there's no problem

**Comment by Alatyami** [comment]
Everything is in our GitHub wiki. We have the repo open for forking so that if the community wants to contribute to it they can. We just do not have the bandwidth to maintain both 1.12 and 1.15+.

**Comment by gatoborrachon** [comment]
oh, well, no problem, many thanks anyways, i just found this mod because of Heat&Climate, you really need to try that mod

thanks for reading, i will check the wiki

**Comment by gatoborrachon** [comment]
even if i wanted, i can't do much for adding compat with that mod, i only know a bit of java and i don't have time since i started university (although oreDict helps a lot)

**Comment by gatoborrachon** [comment]
sorry, i found that the Growthcraft Confectionery page is empty, this content is unfinished too in the mod? (i can't confirm this by myself since i don't know what exactly do)

**Comment by gatoborrachon** [comment]
mmm, for some reason many of the machines (culture jar, cheese vat) are broken, the culture jar cause [soft-crashes](https://pastebin.com/G04uQsVd) and the cheese vat crash without crash report... (
[latest.log](https://github.com/GrowthcraftCE/Growthcraft-1.12/files/5898314/latest.log)
)
