### ISSUE TITLE
java.lang.IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by Analuv** [GrowthcraftCE/Growthcraft-1.12#371]
java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Unknown Source)
    at growthcraft.grapes.common.block.BlockGrapeBlock.func_149745_a(BlockGrapeBlock.java:109)
[crash-2021-04-24_17.51.09-server.txt](https://github.com/GrowthcraftCE/Growthcraft-1.12/files/6372216/crash-2021-04-24_17.51.09-server.txt)

VERSION: growthcraft-1.7.10-2.7.2-complete

**Comment by Alatyami** [comment]
Looks like you are still using Growthcraft for 1.17.10, we haven't touched that source code in almost 3 years. Unfortunately, we have no plans for going back to the 2.7 codebase. Feel free to post this to the right repo, https://github.com/GrowthcraftCE/Growthcraft-1.7/issues
