### ISSUE TITLE
GCCE seems to cause missing textures in Travel Huts

### ISSUE THREAD

**Issue by fivestang** [GrowthcraftCE/Growthcraft-1.12#38]
Hi,
I've found that installing Growthcraft v4.0.4.100 with Travel Huts v3.0.1 causes missing textures on the travel hut glass blocks.  Problem can be reproduced with only those mods and Forge v2768.  Removing GC brings the textures back.

Reported [here](https://github.com/HenryLoenwind/TravelHut/issues/5#issuecomment-431283514).

**Comment by Avatair** [comment]
Based on the linked issue, it was resolved and can be closed here as well.
