### ISSUE TITLE
Unable to create Sake/Rice Water.

### ISSUE THREAD

**Issue by TonyArcane** [GrowthcraftCE/Growthcraft-1.12#380]
![2022-03-16_17 52 06](https://user-images.githubusercontent.com/101765672/158715570-8c1807dd-2ab0-4c29-b1d8-3c4e0e73bd56.png)
Sake/rice water doesn't seem to be working correctly. Also side note there is no recipe for cooked rice. Not sure  about it but I am using the latest version available on the overwolf/twitch launcher. Please let me know if this is a bug that I have found or if it is a duplicate?### ###

**Comment by Alatyami** [comment]
We haven't implemented Growthcraft Rice yet, except for a handful of the items. Once we finish up Growthcraft Milk, Rice is the last to be completed. We'll use this ticket to track the progress.

**Comment by TonyArcane** [comment]
Thank you, Also Just saying some JEI integration would be lovely as looking through the wiki all the time when trying to re learn the mod cause I used to play the OG mod and some things here are the same yet different.

**Comment by Alatyami** [comment]
TonyArcane .... is this issue intended for Growthcraft for Minecraft 1.12 or 1.16?

**Comment by gatoborrachon** [comment]
+the water texture on the pic he provided seems to be 1.13+ (or maybe it is too stretched?), but the textures of the blocks are from 1.12-

+I will test this thing right now since i have the oportunity, give me a moment 
-(but yeah, 1.12 JEI support would be neat, but i also know that the recipe system of Growthcraft 1.12 is fundamentally incompatible with JEI, that would require a rewrite and i know that 1.12 is bug-fixes only, no problem)

**Comment by TonyArcane** [comment]
Gatoborrachon is correct this is 1.12.2 to be specific though I guess I could be missing something
 though this isn't this only issue I have ran into as of recent. For what ever reason none of the Milk liquids can't be fermented into kumis.

**Comment by gatoborrachon** [comment]
are you using OpenJ9?

**Comment by TonyArcane** [comment]
Openj9? I am using the latest version of java that is all I know.

**Comment by gatoborrachon** [comment]
ok, that's fine

~~Have you added the Brew Kettle Lid to the Brew Kettle?~~

My bad, by the pic you shared, you haven't added the Lid to the Brew Kettle, it's necessary to process the Rice

**Comment by gatoborrachon** [comment]
Also @Alatyami, regarding to the JEI compat, i don't want to be a pain in the rear, but in case you are interested in adding it despite the difficult of the issue, i could recommend you to ask here: https://cleanroommc.com/

It's a group of modders focused in 1.12 modding/modpack making, but they use JEI a lot (they even have a fork: HEI), so i can only think that there's no better place to ask about 1.12 JEI compat than there

**Comment by TonyArcane** [comment]
Yeah seems that way like I said before I am way more used to the old way of making Sake so this is my fuck up that and it doesn't help that there is no in game way to know I need the brew kettle lid. You used to be able to put rice straight in and young sake was made and put rice in the furnace to get cooked rice.

**Comment by gatoborrachon** [comment]
Well, we will always have the wiki: https://github.com/GrowthcraftCE/Growthcraft-1.12/wiki/Growthcraft-Rice

But yeah, it isn't so practical when you are in-game, maybe a book like Patchouli or [Guidebook](https://www.curseforge.com/minecraft/mc-mods/guidebook) could help, if not, there could be at least some advices in the **Information** JEI tab

**Comment by TonyArcane** [comment]
Very much so, I agree with that. though I have a small question, Is there a compatibility issue with other mods that add a milk liquid cause I can't seem to ferment milk into Kumis and I am thinking that Tinkers Construct may be the issue.

**Comment by gatoborrachon** [comment]
Well, i honestly have no idea, the [wiki](https://github.com/GrowthcraftCE/Growthcraft-1.12/wiki/Growthcraft-Milk#kumis) doesn't say anything about it more than what it is, i don't even knew about its existence until now, but you could test it and tell us what happened (removing TCon temporally)

**Comment by Alatyami** [comment]
Because this is for 1.12 ..... have you deleted your recipe configs and let them rebuild?

The old way that we implemented the mod made it very difficult to do JEI compatibility. We tried it a couple of times.

Growthcraft for 1.16+ has JEI integration.

**Comment by TonyArcane** [comment]
> Because this is for 1.12 ..... have you deleted your recipe configs and let them rebuild?
> 
> The old way that we implemented the mod made it very difficult to do JEI compatibility. We tried it a couple of times.
> 
> Growthcraft for 1.16+ has JEI integration.

No this is for a premade pack that I am helping with play testing. That issue has come up and talked to the pack dev about it.
The only recipes that showed were crafting table and furnace recipes and nothing else.


> Well, i honestly have no idea, the [wiki](https://github.com/GrowthcraftCE/Growthcraft-1.12/wiki/Growthcraft-Milk#kumis) doesn't say anything about it more than what it is, i don't even knew about its existence until now, but you could test it and tell us what happened (removing TCon temporally)

I will give it a try but we will see what happens

**Comment by TonyArcane** [comment]
> Well, i honestly have no idea, the [wiki](https://github.com/GrowthcraftCE/Growthcraft-1.12/wiki/Growthcraft-Milk#kumis) doesn't say anything about it more than what it is, i don't even knew about its existence until now, but you could test it and tell us what happened (removing TCon temporally)

So I just finished the test and turns out Milk isn't fermentable and it seems like Kumis is just not able to be made in the 1.12 version.
