### ISSUE TITLE
Cellar: Apples can't go in fruit press (Harvestcraft conflict?)

### ISSUE THREAD

**Issue by Syndaryl** [GrowthcraftCE/Growthcraft-1.12#40]
I'm back!

I can put purple grapes in the fruit press, but I can't put a stack of apples in, nor a single apple.

I have Pam's HarvestCraft 1.12.2za installed, and this version modifies vanilla apples to change their hunger restore value. I think this might have caused a problem here. Perhaps the press should be changed to use listAllApple? (EDIT: she's using cropApple, not listAllApple)

On a related note, Pams grapes can't be pressed either; I expected them to produce purple grape juice.

**Comment by IceDragon200** [comment]
I haven't looked at the code, but it's like the fruit press recipes need to use the OreItemStack instead of the fixed stacks.

This assumes the HarvestCraft registered the apples to the ore dictionary (once gain, I could be wrong, I don't know what the codebase looks like outside of 1.8)

**Comment by Syndaryl** [comment]
The replacement apple gets registered here
https://github.com/MatrexsVigil/harvestcraft/blob/beeca969eea263b2f8754e02015d712bb955df9f/src/main/java/com/pam/harvestcraft/item/ItemRegistry.java
I can't follow how the item replacement works, but it gets registered in the oredict as cropApple. If you register the standard apple as cropApple, you should then be able to use the oredict entry?

**Comment by Syndaryl** [comment]
Aha! No recipe! Let me try adding it.

**Comment by IceDragon200** [comment]
Here is the search I did: 
https://github.com/GrowthcraftCE/Growthcraft-1.12/search?q=pressesFrom&unscoped_q=pressesFrom

If you do manage to fix it, please don't close this issue, as it needs to be added to the code, preferably using the ore

**Comment by Syndaryl** [comment]
I can't seem to find a cider or applejuice fluid. This might be why the recipe doesn't exist.

**Comment by Avatair** [comment]
Apple and honey boozes are not supported. We are working on them now.

**Comment by Alatyami** [comment]
As a follow-up, we use foodApple as the oredictionary for the recipe, Pams Harvestcraft doesn't add pamapple to the dictionary.

**Comment by Syndaryl** [comment]
Pam's harvestcraft doesn't replace the object - tis a Minecraft apple
https://cdn.discordapp.com/attachments/351546615816912896/528998492451110912/unknown.png

**Comment by Syndaryl** [comment]
Not sure what's going on in the back end with pams and the pamApple, but certainly by the time we get to MC it looks like a minecraft:apple.
But I added pamApple to <ore:foodApple> via CraftTweaker and it still doesn't work.

**Comment by Avatair** [comment]
In the latest version, they should work. After updating the mod you need to delete first the subfolder for growthcraft in the config folder to refresh the recipes. Then you can use the press with the new recipes which are created on next launch of Minecraft.

**Comment by Syndaryl** [comment]
Aha, reset the configs and that did the trick, Ta!
