### ISSUE TITLE
Ticking player exception on drinking skim milk

### ISSUE THREAD

**Issue by Syndaryl** [GrowthcraftCE/Growthcraft-1.12#41]
I was able to drink some before, but now when I drink a bottle of skim milk I crash with a ticking player exception.

[latest.log](https://github.com/GrowthcraftCE/Growthcraft-1.12/files/2499235/latest.log)
[crash-2018-10-21_09.48.02-server.txt](https://github.com/GrowthcraftCE/Growthcraft-1.12/files/2499236/crash-2018-10-21_09.48.02-server.txt)

**Comment by Syndaryl** [comment]
Ah. I have full hunger (but not full saturation) - this is probably why it's crashing.

Expected behavior is that either it would prevent me from drinking (like vanilla food) or it would behave like buttermilk and allow me to eat and increase my stats without crashing.

**Comment by IceDragon200** [comment]
That's bizarre https://github.com/GrowthcraftCE/Growthcraft-1.12/blob/b0da6ade18bca125d1611dc7511ce0e4467dcca2/src/main/java/growthcraft/core/shared/item/GrowthcraftItemFoodBase.java#L96

I don't know how that line works actually, but I'm going to assume something is funky about that call

Just from the surrounding it's signature would be `addStats(Item, ItemStack)`, which is redundant, as you can get the item from the `ItemStack` with `getItem()`, maybe someone else knows what's up with that

**Comment by Syndaryl** [comment]
Update: I did some experimenting and I crash even if I don't have full hunger - even if I have lost a substantial amount of hunger and can't possibly "Overflow".

**Comment by DWX12** [comment]
I'm using the latest Dev build "growthcraft-1.12.2-4.0.4.200.DEV.77869ce" and believe my crashing is related to this issue:
https://paste.dimdev.org/ahecerehef.mccrash

**Comment by Syndaryl** [comment]
If I had to guess, it would be AppleCore - which is a popular mod that relates directly to food. Other items (growthcraft or no) do not create the issue, which is odd.

**Comment by Avatair** [comment]
Tested it now with only AppleCore, but it worked. Maybe it is some other coremod or a different mod is influencing the AppleCore behavior.

**Comment by renadi** [comment]
Sounds like an ordinary potion ID conflict.

**Comment by Syndaryl** [comment]
Still getting it with the current build. I'll look into potion ID conflict

**Comment by Avatair** [comment]
Well. All logs presented here are indicating that coremods are used. Please find and disable the responsible coremod first.

Obviously a coremod overwriting net.minecraft.util.FoodStats.addStats() is causing the crash. This is the original MC method:
```
    public void addStats(ItemFood foodItem, ItemStack stack)
    {
        this.addStats(foodItem.getHealAmount(stack), foodItem.getSaturationModifier(stack));
    }
```

A null pointer exception can't occur here, because _foodItem_ is never null when calling
```
player.getFoodStats().addStats(this, stack);
```
And _stack_ is not used directly in the method. If a null pointer exception would occur in connection to it, then it would do so inside _getHealAmount()_ or _getSaturationModifier()_, but not in _addStats()_.

**Comment by Syndaryl** [comment]
So here's the fun thing. I copied my profile and removed *all* the coremods (and their dependents). No surprise, the crash goes away.

However, I add them back one-by-one to find the offender, and the crash has not reappeared yet. (As mentioned in the original report, it works for a while, then abruptly stops.)

Going through the code, I'm pretty certain it's AppleCore - but it works with other foods and drinks from Growthcraft and other mods, and it even works with Skim Milk ... for a while. And then it never works again and I have no idea why.

**Comment by Alatyami** [comment]
Do you have a new crash log without the coremods?

**Comment by Syndaryl** [comment]
Trying to provoke it. I think it's going to take a few hours of playtime.

**Comment by Syndaryl** [comment]
Stripping it down to just AppleCore and Growthcraft certainly doesn't do it, even though AppleCore definitely hooks in to all the food stuff.

**Comment by DWX12** [comment]
I apologize for not getting back to this issue as I've had alot going on the past month plus the holiday season.

A question I wondering is if this is some issue to do with Applecore, then would there be a similar issue with Appleskin?

**Comment by Syndaryl** [comment]
Appleskin makes no core edits. It is just a cosmetic client-side mod.

**Comment by Syndaryl** [comment]
It logically must be AppleCore, but I don't know why it'll be happy for hours and then suddenly crap out, and ONLY on skim milk. So I'm digging around in the code.
A new event is injected at:

`https://github.com/squeek502/AppleCore/blob/ca79594242d1e8432badc7e0fc5b44f0f0692331/java/squeek/applecore/asm/module/ModuleFoodStats.java#L289`

Said event is hiding over here:

`https://github.com/squeek502/AppleCore/blob/ca79594242d1e8432badc7e0fc5b44f0f0692331/java/squeek/applecore/asm/Hooks.java#L261`

and that FoodValues that gets instantiated is
`https://github.com/squeek502/AppleCore/blob/ca79594242d1e8432badc7e0fc5b44f0f0692331/java/squeek/applecore/api/food/FoodValues.java#L26`

But that means either player is null (doesn't make sense) or the int and float hunger and saturation values are null, which isn't a thing.

**Comment by Alatyami** [comment]
I'm going to close this one out as i think everyone agrees that it is to an external core mod from Growthcraft.
