### ISSUE TITLE
No recipe to turn ricotta curds into ricotta

### ISSUE THREAD

**Issue by Syndaryl** [GrowthcraftCE/Growthcraft-1.12#42]
After drying ricotta curds we used to craft them with bowls to make ricotta. In JEI I can see the ricotta icon, which still has a bowl, but JEI shows no recipe to make it.

I experimented with pressing it in the cheese press but (as expected) nothing happened.

**Comment by IceDragon200** [comment]
You're suppose to just craft it with a bowl and it gives the ricotta, unless the recipe is missing...

**Comment by Syndaryl** [comment]
Tried crafting it with a bowl, no joy. Checking out the recipe via CraftTweaker, and it shows there is a shapeless recipe... with an empty array for the input.
Looks like the recipe is built at https://github.com/GrowthcraftCE/Growthcraft-1.12/blob/d1aace00cbe98ec501be001c80cb5d974a93196d/src/main/java/growthcraft/milk/common/Init.java#L753; ShapelessItemComparableRecipe only seems to be used for the ricotta, which is interesting.

**Comment by Avatair** [comment]
Should work when curd is dried first. Then you need to use 4 bowls for crafting.
