### ISSUE TITLE
Brewing / Fermenting leads to intoxicated booze if using an invalid ingredient

### ISSUE THREAD

**Issue by Avatair** [GrowthcraftCE/Growthcraft-1.12#44]
Actually only origin yeast leads to such outcome. But what would be if intoxication is an outcome of using an invalid ingredient or an invalid process step?

Something like a default recipe handler is needed to catch unhandled processing steps. Unhandled is meant in the sence that it is not covered by some recipe.

For yeasts we could also add something like this. For example a default handler would be that a spoiled yeast is produced in case of using an improper fluid.

**Comment by Alatyami** [comment]
I'd suggest that an invalid recipe leads to poisoned.

**Comment by Avatair** [comment]
Brewing and fermentation work so far. Need a spoiling feature for yeasts to finish the task.

**Comment by Deshiba** [comment]
Hopefully spoilage would be a completely optional option.

**Comment by Avatair** [comment]
We can add a configuration option to disable spoilage.

**Comment by Avatair** [comment]
Configuration added. Feature can be disabled in growthcraft-cellar.cfg

**Comment by Avatair** [comment]
Implemented for boozes. For yeasts a follow up issue must be created.
