### ISSUE TITLE
Server restart when player break kettle from Grothcraft

### ISSUE THREAD

**Issue by egori477** [GrowthcraftCE/Growthcraft-1.12#51]
Server restart when player break kettle from Grothcraft. Spongeforge
---
Проблема на сервере, когда пытаешься разрушить котел из Grothcraft.

```
28.11 15:23:10 [Server] Server thread/FATAL [minecraft/MinecraftServer]: Error executing task
28.11 15:23:10 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: lidSteamEmitter
28.11 15:23:10 [Server] INFO at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_131]
28.11 15:23:10 [Server] INFO at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_131]
28.11 15:23:10 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
28.11 15:23:10 [Server] INFO at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:294) [SpongeImplHooks.class:1.12.2-2768-7.1.2]
28.11 15:23:10 [Server] INFO at net.minecraft.server.MinecraftServer.redirect$onRun$zjk000(MinecraftServer.java:3970) [MinecraftServer.class:?]
28.11 15:23:10 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
28.11 15:23:10 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
28.11 15:23:10 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
28.11 15:23:10 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
28.11 15:23:10 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
28.11 15:23:10 [Server] INFO Caused by: java.lang.NoSuchFieldError: lidSteamEmitter
28.11 15:23:10 [Server] INFO at growthcraft.cellar.common.tileentity.TileEntityBrewKettle.<init>(TileEntityBrewKettle.java:73) ~[TileEntityBrewKettle.class:?]
28.11 15:23:10 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
28.11 15:23:10 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_131]
28.11 15:23:10 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_131]
28.11 15:23:10 [Server] INFO at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_131]
28.11 15:23:10 [Server] INFO at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_131]
28.11 15:23:10 [Server] INFO at growthcraft.core.shared.block.GrowthcraftBlockContainer.func_149915_a(GrowthcraftBlockContainer.java:595) ~[GrowthcraftBlockContainer.class:?]
28.11 15:23:10 [Server] INFO at net.minecraft.block.Block.createTileEntity(Block.java:1274) ~[aow.class:?]
28.11 15:23:10 [Server] INFO at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:782) ~[axw.class:?]
28.11 15:23:10 [Server] INFO at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:800) ~[axw.class:?]
28.11 15:23:10 [Server] INFO at net.minecraft.world.World.func_175625_s(World.java:5862) ~[amu.class:?]
28.11 15:23:10 [Server] INFO at growthcraft.core.shared.block.GrowthcraftBlockContainer.getTileEntity(GrowthcraftBlockContainer.java:573) ~[GrowthcraftBlockContainer.class:?]
28.11 15:23:10 [Server] INFO at growthcraft.cellar.common.block.BlockBrewKettle.func_176221_a(BlockBrewKettle.java:227) ~[BlockBrewKettle.class:?]
28.11 15:23:10 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185899_b(BlockStateContainer.java:423) ~[awu$a.class:?]
28.11 15:23:10 [Server] INFO at net.minecraft.world.WorldServer.createSnapshot(WorldServer.java:2556) ~[oo.class:?]
28.11 15:23:10 [Server] INFO at org.spongepowered.api.world.extent.Extent.createSnapshot(Extent.java:255) ~[Extent.class:1.12.2-2768-7.1.2]
28.11 15:23:10 [Server] INFO at org.spongepowered.api.world.Location.createSnapshot(Location.java:724) ~[Location.class:1.12.2-2768-7.1.2]
28.11 15:23:10 [Server] INFO at org.spongepowered.common.event.tracking.phase.packet.player.InteractionPacketState.populateContext(InteractionPacketState.java:89) ~[InteractionPacketState.class:1.12.2-2768-7.1.2]
28.11 15:23:10 [Server] INFO at org.spongepowered.common.event.tracking.phase.packet.player.InteractionPacketState.populateContext(InteractionPacketState.java:75) ~[InteractionPacketState.class:1.12.2-2768-7.1.2]
28.11 15:23:10 [Server] INFO at org.spongepowered.common.event.tracking.phase.packet.PacketPhase.populateContext(PacketPhase.java:230) ~[PacketPhase.class:1.12.2-2768-7.1.2]
28.11 15:23:10 [Server] INFO at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:187) ~[PacketPhaseUtil.class:1.12.2-2768-7.1.2]
28.11 15:23:10 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlg000(SourceFile:539) ~[hv$1.class:?]
28.11 15:23:10 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
28.11 15:23:10 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_131]
28.11 15:23:10 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_131]
28.11 15:23:10 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
28.11 15:23:10 [Server] INFO ... 7 more
28.11 15:23:10 [Server] Server thread/ERROR [minecraft/MinecraftServer]: Encountered an unexpected exception
28.11 15:23:10 [Server] INFO java.lang.NoSuchFieldError: lidSteamEmitter
28.11 15:23:10 [Server] INFO at growthcraft.cellar.common.tileentity.TileEntityBrewKettle.<init>(TileEntityBrewKettle.java:73) ~[TileEntityBrewKettle.class:?]
28.11 15:23:10 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
28.11 15:23:10 [Server] INFO at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_131]
28.11 15:23:10 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_131]
28.11 15:23:10 [Server] INFO at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_131]
28.11 15:23:10 [Server] INFO at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_131]
28.11 15:23:10 [Server] INFO at growthcraft.core.shared.block.GrowthcraftBlockContainer.func_149915_a(GrowthcraftBlockContainer.java:595) ~[GrowthcraftBlockContainer.class:?]
28.11 15:23:10 [Server] INFO at net.minecraft.block.Block.createTileEntity(Block.java:1274) ~[aow.class:?]
28.11 15:23:10 [Server] INFO at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:782) ~[axw.class:?]
28.11 15:23:10 [Server] INFO at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:800) ~[axw.class:?]
28.11 15:23:10 [Server] INFO at net.minecraft.world.World.func_175625_s(World.java:5862) ~[amu.class:?]
28.11 15:23:10 [Server] INFO at growthcraft.core.shared.block.GrowthcraftBlockContainer.getTileEntity(GrowthcraftBlockContainer.java:573) ~[GrowthcraftBlockContainer.class:?]
28.11 15:23:10 [Server] INFO at growthcraft.cellar.common.block.BlockBrewKettle.func_176221_a(BlockBrewKettle.java:227) ~[BlockBrewKettle.class:?]
28.11 15:23:10 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185899_b(BlockStateContainer.java:423) ~[awu$a.class:?]
28.11 15:23:10 [Server] INFO at net.minecraft.world.WorldServer.createSnapshot(WorldServer.java:2556) ~[oo.class:?]
28.11 15:23:10 [Server] INFO at org.spongepowered.api.world.extent.Extent.createSnapshot(Extent.java:255) ~[Extent.class:1.12.2-2768-7.1.2]
28.11 15:23:10 [Server] INFO at org.spongepowered.api.world.Location.createSnapshot(Location.java:724) ~[Location.class:1.12.2-2768-7.1.2]
28.11 15:23:10 [Server] INFO at net.minecraft.server.MinecraftServer.handler$onServerTickEnd$zjk000(MinecraftServer.java:3795) ~[MinecraftServer.class:?]
28.11 15:23:12 [Multicraft] Server shut down (starting)
28.11 15:23:12 [Multicraft] Restarting crashed server in 5 seconds
```

**Comment by IceDragon200** [comment]
Appears that the `lidSteamEmitter` is being referenced on the server, I assume this should be a CLIENT only reference.

This is only based on the stacktrace you provided

**Comment by Avatair** [comment]
It is a SideOnly issue which has been fixed a few days ago. Same happens with curds too. Seems like the latest version is not released.

**Comment by Alatyami** [comment]
Release will be pushed out this weekend.

**Comment by egori477** [comment]
New problem with kettle. After problem with it. I replace server platform from sponge into forge only. And.. now when player jum in kellte (inside) - client out of the server! AND enother problem World Edit and server Admin (I) can't broke or replace or delete this HELL-kettle. One player was jum on this kettle... Now that player can't enter on server.

Console, when I try to break the kettle in CREATIV mode (Of course, it does not break)!
> 02.12 17:59:39 [Server] Server thread/ERROR [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$LeftClickBlock@3c84cefe:
02.12 17:59:39 [Server] INFO java.lang.NoSuchFieldError: lidSteamEmitter
02.12 17:59:39 [Server] INFO at growthcraft.cellar.common.tileentity.TileEntityBrewKettle.<init>(TileEntityBrewKettle.java:73) ~[TileEntityBrewKettle.class:?]
02.12 17:59:39 [Server] INFO at sun.reflect.GeneratedConstructorAccessor165.newInstance(Unknown Source) ~[?:?]
02.12 17:59:39 [Server] INFO at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_131]
02.12 17:59:39 [Server] INFO at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_131]
02.12 17:59:39 [Server] INFO at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_131]
02.12 17:59:39 [Server] INFO at growthcraft.core.shared.block.GrowthcraftBlockContainer.func_149915_a(GrowthcraftBlockContainer.java:595) ~[GrowthcraftBlockContainer.class:?]
02.12 17:59:39 [Server] INFO at net.minecraft.block.Block.createTileEntity(Block.java:1274) ~[aow.class:?]
02.12 17:59:39 [Server] INFO at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:782) ~[axw.class:?]
02.12 17:59:39 [Server] INFO at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:800) ~[axw.class:?]
02.12 17:59:39 [Server] INFO at net.minecraft.world.World.func_175625_s(World.java:2399) ~[amu.class:?]
02.12 17:59:39 [Server] INFO at noppes.npcs.api.wrapper.BlockWrapper.<init>(BlockWrapper.java:156) ~[BlockWrapper.class:?]
02.12 17:59:39 [Server] INFO at noppes.npcs.api.wrapper.BlockWrapper.createNew(BlockWrapper.java:285) ~[BlockWrapper.class:?]
02.12 17:59:39 [Server] INFO at noppes.npcs.api.wrapper.WrapperNpcAPI.getIBlock(WrapperNpcAPI.java:104) ~[WrapperNpcAPI.class:?]
02.12 17:59:39 [Server] INFO at noppes.npcs.ScriptPlayerEventHandler.invoke(ScriptPlayerEventHandler.java:97) ~[ScriptPlayerEventHandler.class:?]
02.12 17:59:39 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_430_ScriptPlayerEventHandler_invoke_LeftClickBlock.invoke(.dynamic) ~[?:?]
02.12 17:59:39 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
02.12 17:59:39 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
02.12 17:59:39 [Server] INFO at net.minecraftforge.common.ForgeHooks.onLeftClickBlock(ForgeHooks.java:1116) [ForgeHooks.class:?]
02.12 17:59:39 [Server] INFO at net.minecraft.server.management.PlayerInteractionManager.func_180784_a(PlayerInteractionManager.java:141) [or.class:?]
02.12 17:59:39 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:693) [pa.class:?]
02.12 17:59:39 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:40) [lp.class:?]
02.12 17:59:39 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerDigging.func_148833_a(SourceFile:10) [lp.class:?]
02.12 17:59:39 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
02.12 17:59:39 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
02.12 17:59:39 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
02.12 17:59:39 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
02.12 17:59:39 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
02.12 17:59:39 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
02.12 17:59:39 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
02.12 17:59:39 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
02.12 17:59:39 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
02.12 17:59:39 [Server] Server thread/ERROR [FML]: Index: 7 Listeners:
02.12 17:59:39 [Server] Server thread/ERROR [FML]: 0: HIGHEST
02.12 17:59:39 [Server] Server thread/ERROR [FML]: 1: ASM: class io.chocorean.authmod.event.Handler onPlayerEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent;)V
02.12 17:59:39 [Server] Server thread/ERROR [FML]: 2: HIGH
02.12 17:59:39 [Server] Server thread/ERROR [FML]: 3: ASM: class com.feed_the_beast.ftbutilities.handlers.FTBUtilitiesPlayerEventHandler onBlockLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
02.12 17:59:39 [Server] Server thread/ERROR [FML]: 4: NORMAL
02.12 17:59:39 [Server] Server thread/ERROR [FML]: 5: ASM: class thaumcraft.common.lib.events.ToolEvents playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
02.12 17:59:39 [Server] Server thread/ERROR [FML]: 6: ASM: class team.chisel.common.item.ChiselController onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
02.12 17:59:39 [Server] Server thread/ERROR [FML]: 7: ASM: noppes.npcs.ScriptPlayerEventHandler@4eaefff5 invoke(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
02.12 17:59:39 [Server] Server thread/ERROR [FML]: 8: ASM: vazkii.botania.common.item.rod.ItemExchangeRod@6e13375d onLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
02.12 17:59:39 [Server] Server thread/ERROR [FML]: 9: ASM: class WayofTime.bloodmagic.util.handler.event.GenericHandler onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
02.12 17:59:39 [Server] Server thread/ERROR [FML]: 10: ASM: class WayofTime.bloodmagic.util.handler.event.LivingArmourHandler onPlayerClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
02.12 17:59:39 [Server] Server thread/ERROR [FML]: 11: ASM: crafttweaker.mc1120.events.CommonEventHandler@75e7bd8f onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
02.12 17:59:39 [Server] Server thread/ERROR [FML]: 12: ASM: com.sk89q.worldedit.forge.ForgeWorldEdit@53a181b3 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
02.12 17:59:39 [Server] Server thread/ERROR [FML]: 13: ASM: noppes.npcs.ScriptPlayerEventHandler@4eaefff5 forgeEntity(Lnet/minecraftforge/fml/common/eventhandler/Event;)V
02.12 17:59:39 [Server] Server thread/ERROR [FML]: 14: LOW
02.12 17:59:39 [Server] Server thread/ERROR [FML]: 15: ASM: hellfirepvp.astralsorcery.common.event.listener.EventHandlerEntity@335c7f8f onLeftClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$LeftClickBlock;)V
02.12 17:59:39 [Server] Server thread/FATAL [minecraft/MinecraftServer]: Error executing task
02.12 17:59:39 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: lidSteamEmitter
02.12 17:59:39 [Server] INFO at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_131]
02.12 17:59:39 [Server] INFO at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_131]
02.12 17:59:39 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
02.12 17:59:39 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
02.12 17:59:39 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
02.12 17:59:39 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
02.12 17:59:39 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
02.12 17:59:39 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]

**Comment by Alatyami** [comment]
4.0.4.200 has been released 
https://github.com/GrowthcraftCE/Growthcraft-1.12/releases/tag/4.0.4.200
