### ISSUE TITLE
Growthcraft Rice: Rice Paddy Irrigation Bug

### ISSUE THREAD

**Issue by Nakuta** [GrowthcraftCE/Growthcraft-1.12#56]
![untitled](https://user-images.githubusercontent.com/45821621/49871915-7f4eaa00-fde5-11e8-8384-a3b17ff52f82.png)

The south-east corner of a 9x9 grid of rice paddies is not being properly irrigated. Please see the referenced image.

**Comment by Alatyami** [comment]
So, this is an interesting problem. It is all about the math. The max field range is 4, meaning that there has to be a FuildBlock "water" within four blocks. The iterator uses the following range to find the fluid block:
```
x-4, y0, z-4 and x+4, y0, z+4
```
For some reason, in the SW corner, it doesn't think that the Water block is in range. 

Going to change the way it finds the Water block.
