### ISSUE TITLE
Rope Blocks Can Be Passed Through During Certain Behaviors

### ISSUE THREAD

**Issue by Nakuta** [GrowthcraftCE/Growthcraft-1.12#63]
By either walking towards or pressing against a Rope block, you can sometimes pass through the block.  Walking doesn't produce this effect consistently, and pressing against the rope will always eventually allow you to pass through it but the length of time you must press against it is inconsistent. This was tested against a head-height line of Rope blocks.

**Comment by Alatyami** [comment]
This is actually be design. So that you can walk through your orchard. The collision boxes are in the center of the block space, so if you walk where two block spaces meet, you can squeeze through. One thing that is not implemented is a Slowness like spider webs.

**Comment by Alatyami** [comment]
Adding slowness would be too annoying ... closing.
