### ISSUE TITLE
Growthcraft items appear everywhere in the menu.

### ISSUE THREAD

**Issue by MilchLos** [GrowthcraftCE/Growthcraft-1.12#7]
Thanks for porting the mod to Minecraft 1.12. :)
I am currently testing out the mod and so far I have noticed that Growthcraft items appear everywhere in the creative menu:

![2018-05-28_15 25 25](https://user-images.githubusercontent.com/18751835/40616508-ad24547a-628b-11e8-892f-442fd9121229.png)
![2018-05-28_15 25 02](https://user-images.githubusercontent.com/18751835/40616509-ad3c41de-628b-11e8-8a25-a5852f00b233.png)
![2018-05-28_15 25 08](https://user-images.githubusercontent.com/18751835/40616510-ad5478bc-628b-11e8-8a6c-4ffb52d7faf6.png)
![2018-05-28_15 25 16](https://user-images.githubusercontent.com/18751835/40616511-ad6dfb0c-628b-11e8-8fd5-f1ba565e9c64.png)

As you can see Growthcraft items beginning from the _White Crowbar_ to _Ricotta Curds_ appear everywhere. It could be caused by getSubItems now being called by all tabs.

**Comment by Avatair** [comment]
Fixed in recent release published on Discord. It will be published on curseforge, soon.
