### ISSUE TITLE
Serene Seasons Compatibility

### ISSUE THREAD

**Issue by Deshiba** [GrowthcraftCE/Growthcraft-1.12#73]
Currently there is no compatibility with serene season. This is evident by the lack of fertility season annotations in seeds:
![seeds](https://user-images.githubusercontent.com/10565800/50535903-f9ee2800-0b4e-11e9-96e8-55b55800a794.jpg)

And that at least the trees still grow in winter.
![2018-12-29_09 45 06](https://user-images.githubusercontent.com/10565800/50535893-ed69cf80-0b4e-11e9-883c-34bb7b0f2312.png)

I'd like to request compatibility with serene seasons for immersion reasons.

**Comment by Avatair** [comment]
This one will be tricky, because Serene Seasons doesn't provide a suficient API for it.

**Comment by Avatair** [comment]
The SereneSeasons compatibility is not possible out of the box right now by just deploying the jar of GC and SS together into the mods folder. Configuration tweaks are necessary at SS. The SS dev guys proposed me to send them a list of crop fertility for different seasons so they will support them in their next release. I'm about to propose following configuration:
- Spring: **Rice**
- Summer: **Apples**, **Hops**, **Rice**
- Autumn: **Apples**, **Grapes**, **Hops**, **Rice**
- Winter: nothing

@Alatyami @Deshiba @Kisutora 
Please review this list, before I submit it to them.

**Comment by Deshiba** [comment]
Thistle is missing.
And maybe the different grapes could have different seasons. But having them all the same is fine by me.

**Comment by Avatair** [comment]
Forgot to add the Thistle as well.

With the different grape types I'd like to wait until the SereneSeaons guys will advance their API. Actually the color is identified by a meta number, which SereneSeasons is not able to distinguish. Implementing it now means, that it is needed to create different block types for each color.

**Comment by Nakuta** [comment]
Is there a way to turn off honey and honeycomb production during the winter?

**Comment by Deshiba** [comment]
@Nakuta, the bees would be handled in a second pass when the api is further along afaik.

**Comment by Avatair** [comment]
Okay. This is the final list then:
- Spring: Rice
- Summer: Apples, Hops, Rice, Thistles
- Autumn: Apples, Grapes, Hops, Rice, Thistles
- Winter: nothing

**Comment by Avatair** [comment]
The list is now commited at SereneSeasons as well.

**Comment by Avatair** [comment]
Implemented for seeds and growing plants only. For other features, like bee boxes an follow up issue should be opened.
