### ISSUE TITLE
[Bug] Can't craft a pot of honey

### ISSUE THREAD

**Issue by Deshiba** [GrowthcraftCE/Growthcraft-1.12#78]
I'm trying to craft a honey pot following the recipe in The One Probe.
![top craft](https://user-images.githubusercontent.com/10565800/50546490-b23bcf00-0c28-11e9-82cc-32be4e1dad3f.jpg)
When trying this in the tinkers table, nothing happens:
![tinkers table](https://user-images.githubusercontent.com/10565800/50546498-cd0e4380-0c28-11e9-8c94-91fd8dad489a.jpg)
For good measure tested it in the vanilla table too:
![vanilla table](https://user-images.githubusercontent.com/10565800/50546514-0b0b6780-0c29-11e9-92e5-917a465ae961.jpg)

There's a report by a different user in the discord too.

**Comment by Avatair** [comment]
On the vanilla crafting table it works. Is it a tinkers table issue?

**Comment by Deshiba** [comment]
Well the modlist is pretty sparse. I'll try ruling out some likely suspects

![modlist](https://user-images.githubusercontent.com/10565800/50551938-8b61b500-0c89-11e9-8d35-6ea2e9335185.jpg)

**Comment by Deshiba** [comment]
I can't reproduce this with the same list in Single player, seems to only appear on multiplayer.

![2018-12-30_23 44 10](https://user-images.githubusercontent.com/10565800/50552123-dc26dd00-0c8c-11e9-9933-244f42e65876.png)

**Comment by Alatyami** [comment]
I'll test it in my modpack server ... Takes a while to load 107 mods.

**Comment by Alatyami** [comment]
We'll have to check it out ... this might be an issue similar to Ricotta where the recipe calls for one item ID but the actuall id with meta is something else.

**Comment by Avatair** [comment]
It is a small SideOnly issue

**Comment by Avatair** [comment]
Fixed.
