### ISSUE TITLE
Multiple Bugs

### ISSUE THREAD

**Issue by MilchLos** [GrowthcraftCE/Growthcraft-1.12#8]
The butter churn is not working as I can't interact with it or insert a bucket of milk. Also when breaking the churn, the particles don't have any textures:
![2018-05-28_18 32 45](https://user-images.githubusercontent.com/18751835/40623141-a229f268-62a5-11e8-9965-8fba84b98ae4.png)

The cheese vat doesn't work when Forestry is enabled. The vat will not be filled with milk unless Forestry is disabled. Unfortunately it isn't just Forestry. Other mods which I can't identify blocks milk from being inserted as well. 

Some items are missing their localisation (I believe that is what it's called; not a native speaker) or The One Probe integration is not working:
![2018-05-28_18 14 32](https://user-images.githubusercontent.com/18751835/40623042-1bc8843c-62a5-11e8-8cbe-e7828a8c4792.png)
![2018-05-28_18 18 56](https://user-images.githubusercontent.com/18751835/40623045-2185c8a8-62a5-11e8-9028-de3a985f6949.png)
![2018-05-28_18 20 07](https://user-images.githubusercontent.com/18751835/40623047-23f17d94-62a5-11e8-8afe-41cfc17db0a4.png)
![2018-05-28_18 20 20](https://user-images.githubusercontent.com/18751835/40623049-25eabb1a-62a5-11e8-9d51-c3ea0b1163d4.png)

**Comment by Avatair** [comment]
Fluid handling for churns have been fixed, now. But milk won't be insertable anyway. Instead cream should work,

**Comment by Avatair** [comment]
Forestry conflicts has been solved as well. The issue was that the milk fluid was registered by it as well.

**Comment by Alatyami** [comment]
In reviewing this issue the final items need to be resolved so we can close this one out:
* Missing item texture for Gorgonzola Cheese (Unaged) growthcraft_milk:cheese_aged
* Missing item texture for Cheddar Cheese (Unaged) growthcraft_milk:cheese_waxed
* Missing item texture for Gorgonzola Curds growthcraft_milk:curds_aged
* Missing item texture for Cheddar Curds growthcraft_milk:curds_waxed
* Missing item texture for Ricotta Curds growthcraft_milk:curds_simple
* Missing JEI/One Probe Block Texture for Cheese Press

**Comment by Deshiba** [comment]
@Alatyami your last comment has some overlap with  #81, also look at the cheese variants with a piece missing. I believe that's [cheese].cut.name <- can't check in game r/n

**Comment by Avatair** [comment]
About the missing textures in One Probe. It assumes, that every block has also a block item. If not then missing textures are shown. Underground Biomes Constructs does have issues with One Probe as well. Shall we treat this one as a bug anyway?

**Comment by Alatyami** [comment]
I think so.
