### ISSUE TITLE
[Bug] Snow on fences with ropes

### ISSUE THREAD

**Issue by Deshiba** [GrowthcraftCE/Growthcraft-1.12#82]
Fences with ropes can accumulate snow in a snowy biome or in serene seasons winter. I placed vanilla fences next to them for reference.

![2018-12-30_13 26 04](https://user-images.githubusercontent.com/10565800/50547242-afe07180-0c36-11e9-8f99-a1a9f30f5e19.png)

**Comment by Avatair** [comment]
Also I see that we need fence connection to rope knots :)

**Comment by Avatair** [comment]
Fixed.
