### ISSUE TITLE
[Balance] Hops

### ISSUE THREAD

**Issue by Deshiba** [GrowthcraftCE/Growthcraft-1.12#85]
Hops seem to drop around 3 to 8 per growth per plant. A setup like below will pretty much gives you a over a stack a minecraft day. With the brewing of ale taking a long time and not requiring a lot of hops you will quickly have a major surplus of the stuff.
![2018-12-30_15 51 18](https://user-images.githubusercontent.com/10565800/50548426-83cfeb00-0c4c-11e9-9138-3b2041f5cdee.png)

I'd suggest lowering the amount of hops dropped to 1 per harvest or increasing the amount needed for brewing.

**Comment by Alatyami** [comment]
Going to add the output count as a config item.

**Comment by Deshiba** [comment]
Might be wise to have all the crops be configurable, could be handy for specific packs.
