### ISSUE TITLE
Apple Trees-Minor Bugs

### ISSUE THREAD

**Issue by WenXin20** [GrowthcraftCE/Growthcraft-1.12#95]
Forge v14.23.5.2796-1.12.2
Growthcraft v4.0.4.300

- Apple Tree leaves don't despawn after the logs are cut down.
- Apples on the tree also can't be seen by Waila despite being highlighted by the cursor.
  - Perhaps Waila could also show when an apple is mature.
- Leaves are gray in the inventory

![2019-01-01_18 03 13](https://user-images.githubusercontent.com/12000593/50577523-8a4a9800-0def-11e9-817e-ecaba44017f4.png)

**Comment by Avatair** [comment]
Point 1 and 3 are solved.

**Comment by Alatyami** [comment]
![2019-06-22_12 17 00](https://user-images.githubusercontent.com/1868411/59966256-d5647e80-94e7-11e9-9e71-5f88f9c95da2.png)
