### ISSUE TITLE
Bamboo Trees-Minor Bugs

### ISSUE THREAD

**Issue by WenXin20** [GrowthcraftCE/Growthcraft-1.12#96]
Forge v14.23.5.2796-1.12.2
Growthcraft v4.0.4.300

- Bamboo Tree leaves don't despawn after the logs are cut down.
- Leaves are gray instead of having the biome color.
- Leaves are also gray in the inventory.
- Leaves drop leaf blocks when broken instead of saplings.

![2019-01-01_13 22 19](https://user-images.githubusercontent.com/12000593/50577573-4f952f80-0df0-11e9-9dcf-e30cfd6f4250.png)

**Comment by Alatyami** [comment]
Just confirmed .... Bamboo leaves have the correct green texture.
