### ISSUE TITLE
Needs a way to convert from fluid honey to honey pot

### ISSUE THREAD

**Issue by Syndaryl** [GrowthcraftCE/Growthcraft-1.12#99]
Honey pot can be converted to forge bucket of honey fluid. Once in this form, it cannot be used by other mods. There *are* conversion recipes in e.g. Harvestcraft for honeypot to Harvestcraft honey. Honey Pot -> bucket of Honey should be a round-trip conversion.

**Comment by Avatair** [comment]
Recipes for Honey containers have been fixed and improved. The changes are actually on the dev branch.

**Comment by Avatair** [comment]
Implemented by https://github.com/GrowthcraftCE/Growthcraft-1.12/pull/86 .
